### ISSUE TITLE
Need suggestion for contributing more integrations

### ISSUE THREAD

**Issue by shashanktomar** [NvChad/base46#100]
Hi There,

I am interested in contributing more integrations here. I can start with highlight groups `nvim-notify` and `lsp-saga` plugins. Just want to understand if there are any issues with going forward. 

Are you happy with these integrations being added here even though the plugins are not added to nvchad or do you prefer users adding them as UI overrides.

**Comment by siduck** [comment]
yes I am happy with you adding plugin integrations

**Comment by siduck** [comment]
and you should know that those integrations will not be loaded automatically. Users can load them by just

```lua
require('base46').load_highlight "nvim_notify"
```

This is just an example
