### ISSUE TITLE
vscode_dark theme doesn't match

### ISSUE THREAD

**Issue by JxBP** [NvChad/base46#103]
<details>
<summary>Rust</summary>

 VSCode (Rust)

 ![code](https://user-images.githubusercontent.com/61627369/189401894-68382190-61c2-47c5-bb57-a1595bb13a21.png)

 Neovim (Rust)

 ![neovim](https://user-images.githubusercontent.com/61627369/189401900-7ca26bde-0919-420b-ba6f-4ad0319e6b43.png)
</details>

<details>
<summary>Lua</summary>

VSCode (Lua)

![code_chadrc](https://user-images.githubusercontent.com/61627369/189401898-03e75ab5-2a24-4ce6-9437-c3b2876d20e1.png)

Neovim (Lua)

![neovim_chadrc](https://user-images.githubusercontent.com/61627369/189401902-797c0f96-2345-4375-bbde-3bf0bcea68be.png)
</details>

<details>
<summary>C</summary>

VSCode (C)

![code_c](https://user-images.githubusercontent.com/61627369/189402530-09761062-c30e-4cba-907f-81bcfbc17d73.png)

Neovim (C)

![neovim_c](https://user-images.githubusercontent.com/61627369/189402536-3e120318-af44-4aaa-8e6f-783853c480c7.png)
</details>

I have the vscode_dark theme enabled but the colors don't match VSCode's Dark+ theme (neither the non-plus theme. That's just the same with a few things highlighted less).

Here is also a list of plugin I have installed (besides the one shipped with NvChad).
<details>
<summary>Plugins</summary>

- neovim/nvim-lspconfig
- andweeb/presence.nvim
- jose-elias-alvarez/null-ls.nvim
- mfussenegger/nvim-dap
- rcarriga/nvim-dap-ui
- lostl1ght/rust-tools.nvim
- karb94/neoscroll.nvim
- xiyaowong/nvim-transparent
</details>

**Comment by siduck** [comment]
you sure that you have tsparsers of rust and c installed?

**Comment by JxBP** [comment]
I installed those now but it's still not quite the same as VSCode. Lua (for which the parser was already installed by NvChad or something apparently) also as you can see in the previous screenshots.

![neovim_c_ts](https://user-images.githubusercontent.com/61627369/189415377-bfbb12f0-902f-4308-adea-67a3736221b4.png)
![neovim_rust_ts](https://user-images.githubusercontent.com/61627369/189415379-168d8834-552d-48da-b386-8617ad516619.png)

**Comment by siduck** [comment]
hmm yea its not the same as vscode one, i'll see

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/201499916-9b270a0c-a9e9-44ad-b42e-80acf82a9bf3.png)

**Comment by siduck** [comment]
@JxBP do a packersync and check. And do know that we can match to vscode's theme 100%  cuz of treesitter

**Comment by JxBP** [comment]
I honestly already forgot about this issue and moved to another theme already.
Thank you for improving it though!
