### ISSUE TITLE
Add Dark Horizon colorscheme

### ISSUE THREAD

**Issue by Dereklee0312** [NvChad/base46#112]
# Feature 
I would like to add the Dark Horizon colorscheme to NvChad's base46 as it is quite different from what is currently available, and would probably be used by quite a few.

It has a high contrast and works well with dark backgrounds and I'm guessing transparent ones as well.

The github repo can be found on [Dark Horizon](https://github.com/mcagampan/dark-horizon/blob/master/themes/Dark%20Horizon-color-theme.json)
## Screenshots
![image](https://user-images.githubusercontent.com/80673848/193456451-ea994724-a99c-4173-b410-8565f7149c58.png)

![image](https://user-images.githubusercontent.com/80673848/193456463-9b9bffa6-aaae-4fd8-a790-b085eaa87944.png)

![image](https://user-images.githubusercontent.com/80673848/193456471-07c2db4e-ae37-4d41-8e76-2661457d69cd.png)

**Comment by siduck** [comment]
@Dereklee0312 does this have a base16 format? :thinking:

**Comment by Dereklee0312** [comment]
> @Dereklee0312 does this have a base16 format? 🤔

Not sure about that, I'm completely new with the whole colorscheme and highlighting groups shenanigans. I'll try to figure it out whenever possible.
