### ISSUE TITLE
Falcon Theme

### ISSUE THREAD

**Issue by kavinvalli** [NvChad/base46#117]
Hi, I'm not entirely sure how to port this but I recently came across [fenetikm/falcon](https://github.com/fenetikm/falcon) and it looks like something I'd want to try out but I'm not able to use an external theme in NVChad. Would love if someone could help me port this to base46!

![image](https://user-images.githubusercontent.com/41034356/194686777-dbf120dd-6530-4f4f-8308-74f561ffd589.png)

**Comment by siduck** [comment]
hi there, check the contribution guide https://github.com/NvChad/base46#contribute-for-new-themes

Just get all the hex colors from falcon theme and then add them in your PORT & PR and I'll improve the PR if it needs changes.

**Comment by kavinvalli** [comment]
> hi there, check the contribution guide https://github.com/NvChad/base46#contribute-for-new-themes
> 
> Just get all the hex colors from falcon theme and then add them in your PORT & PR and I'll improve the PR if it needs changes.

It's really confusing since I haven't worked with colorschemes a lot and the falcon palette is pretty confusing. Would love if someone could help with this!

Also, I did try just disabling Nvchad/base46 and then setting `colorscheme falcon` but it turns out that plugins like nvim-tree, telescope don't get updated with the new colorscheme.
Falcon already has support for them, so I don't see any any use in porting it, if I could directly use it.
Is there some way for this @siduck

**Comment by siduck** [comment]
@kavinvalli load falcon theme after base64 then. 

I know falcon already has support for nvimtree etc but not our tabufline, statusline and many other highlight groups. Dont worry I will port the theme tomorrow for u!

**Comment by kavinvalli** [comment]
> @kavinvalli load falcon theme after base64 then.
> 
> I know falcon already has support for nvimtree etc but not our tabufline, statusline and many other highlight groups, and our theme plugin is very fast! We just need their colors. Dont worry I will port the theme tomorrow for u!

That would be great @siduck. Thank you!

**Comment by kavinvalli** [comment]
@siduck Were you able to figure out something?

**Comment by siduck** [comment]
oh sorry i was busy yesterday, will make the theme today

**Comment by kavinvalli** [comment]
> oh sorry i was busy yesterday, will make the theme today

No worries @siduck! Looking forward to check it out!

**Comment by kavinvalli** [comment]
@siduck How is this looking?

**Comment by siduck** [comment]
@kavinvalli put this under `custom/themes/falcon.lua` and select it from theme switcher, let me know if you need any changes

```lua
-- Credits to https://github.com/fenetikm/falcon as its the orignal theme
-- This is a modified version of original theme

local M = {}

M.base_30 = {
  white = "#F8F8FF",
  white2 = "#DFDFE5",
  tan = "#CFC1B2",
  darker_black = "#000015",
  black = "#020222", --  nvim bg
  black2 = "#0b0b2b",
  one_bg = "#161636",
  one_bg2 = "#202040",
  one_bg3 = "#2a2a4a",
  grey = "#393959",
  grey_fg = "#434363",
  grey_fg2 = "#4d4d6d",
  light_grey = "#5c5c7c",
  red = "#FF761A",
  baby_pink = "#FF8E78",
  pink = "#ffafb7",
  line = "#202040", -- for lines like vertsplit
  green = "#9BCCBF",
  vibrant_green = "#b9e75b",
  nord_blue = "#a1bce1",
  blue = "#6699cc",
  yellow = "#FFC552",
  sun = "#FFD392",
  purple = "#99A4BC",
  dark_purple = "#635196",
  teal = "#34BFA4",
  orange = "#f99157",
  cyan = "#BFDAFF",
  statusline_bg = "#0b0b2b",
  lightbg = "#2a2a4a",
  pmenu_bg = "#FFB07B",
  folder_bg = "#598cbf",
}

M.base_16 = {
  base00 = "#020222",
  base01 = "#0b0b2b",
  base02 = "#161636",
  base03 = "#202040",
  base04 = "#e4e4eb",
  base05 = "#eeeef5",
  base06 = "#f3f3fa",
  base07 = "#F8F8FF",
  base08 = "#BFDAFF",
  base09 = "#B4B4B9",
  base0A = "#FFC552",
  base0B = "#C8D0E3",
  base0C = "#B4B4B9",
  base0D = "#FFC552",
  base0E = "#8BCCBF",
  base0F = "#DFDFE5",
}

M.polish_hl = {
  Statement = { fg = M.base_30.purple },
  Type = { fg = M.base_30.white2 },
  Include = { fg = M.base_30.tan },
  Keyword = { fg = M.base_16.base0D },
  TSKeyword = { fg = M.base_16.base0D },
  Operator = { fg = M.base_30.red },
}

vim.opt.bg = "dark"

M = require("base46").override_theme(M, "falcon")

return M
```

**Comment by kavinvalli** [comment]
@siduck seems to be pretty good!

**Comment by siduck** [comment]
pushed it to the repo! enjoy :D

**Comment by kavinvalli** [comment]
Hey @siduck, I dont know if this is an issue but in react, the highlighting is not very distinctive.
![Screenshot 2022-10-25 at 08 53 05](https://user-images.githubusercontent.com/41034356/197674936-bfb79983-f0e3-4685-872d-a09ef0dacd10.png)

**Comment by siduck** [comment]
Hi @kavinvalli , install tsx and typescript tsparser

**Comment by kavinvalli** [comment]
> Hi @kavinvalli , install tsx and typescript tsparser

It seemed to start working after i used an emmet snippet once

**Comment by kavinvalli** [comment]
@siduck any idea why this might be happening. tsx and typescript tsparser are installed already for me. It just seems to start working after runnig an emmet snippet once.

> > Hi @kavinvalli , install tsx and typescript tsparser
> 
> It seemed to start working after i used an emmet snippet once

**Comment by siduck** [comment]
so it works right now or no?

**Comment by kavinvalli** [comment]
Yup, it works @siduck ! Sorry for the inconvenience.
