### ISSUE TITLE
Using templates to automatically generate themes

### ISSUE THREAD

**Issue by JamyGolden** [NvChad/base46#126]
Would it be possible to use templates for themes to automatically generate the themes from https://github.com/tinted-theming/base16-schemes (the way base16 template repositories use the base16-builders and templates) instead of manually creating and maintaining each theme? (I'm asking this as someone who maintains multiple `base16-*` repositories, so I could contribute to this change if you needed any help with it).

**Comment by siduck** [comment]
@JamyGolden its not possible, the themes have to be tested tons of times locally before releasing.

And the values you see here are just rough values, they differ from theme to theme

![image](https://user-images.githubusercontent.com/59060246/196422635-7b49787a-3564-43fa-9cdf-535983672b90.png)

**Comment by bryant-the-coder** [comment]
i think we can like hv a website where we insert the values and it generates a template?

**Comment by JamyGolden** [comment]
@siduck ah ok yeah the theme-to-theme curation definitely makes it a problem to auto generate.

@bryant-the-coder I was wondering if it would be possible to use the [base16-schemes](https://github.com/tinted-theming/base16-schemes) and a [base16-builder](https://github.com/tinted-theming/base16-builder-go) to generate your themes instead of needing to do it manually, like here for example: https://github.com/tinted-theming/base16-vim/tree/main/colors, but since you curate the themes individually that's not possible.
