### ISSUE TITLE
highlights for lazyloaded hlgroups aren't done properly

### ISSUE THREAD

**Issue by lucario387** [NvChad/base46#129]
Basically, if I override some hlgroups of say, treesitter, inside M.ui of chadrc, then load treesitter afterwards, then the hlgroups inside `ui.override` and `ui.add` will be overridden by the defaults.

**Comment by siduck** [comment]
@lucario387 why closed this issue?

**Comment by lucario387** [comment]
Haven't tested properly on why, and when such triggers happened, will open/reopen once I can write more meaningful issues @siduck
