### ISSUE TITLE
packer.nvim fails to update base46

### ISSUE THREAD

**Issue by jfvillablanca** [NvChad/base46#138]
Hello, I was updating and adding new plugins but base46 keeps failing to update. Retrying yields the same fail message.

`✗  Failed to update NvChad/base46`

![Screenshot from 2022-11-13 17-41-12](https://user-images.githubusercontent.com/31008330/201515814-c3afa3ea-2dfd-4aea-be90-28ad63fe09f0.png)

I'm not sure how to reproduce this issue or if this is a packer.nvim issue.

**Comment by siduck** [comment]
re-install that plugin, its a packer.nvim issue. WHenever there's a forced push on the plugin repo, packer complains about this issue i think.

so just `rm -rf ~/.local/share/nvim/site/pack/packer/start/base46` and reopen nvim , do packersync

**Comment by jfvillablanca** [comment]
Thank you!
