### ISSUE TITLE
Strange theme colors preview in .tsx file 

### ISSUE THREAD

**Issue by Tinkerbells** [NvChad/base46#139]
**Description**
I used npx create-t3-app command for initialize my project and found strange theme colors preview in _app.tsx file  

**Desktop** 

 - Arch linux
 - st terminal 
 - NVIM v0.8.0-v0.8.0
  Build type: Release

**Screenshots**
![2022-11-15-16:01:22](https://user-images.githubusercontent.com/55500372/201926000-a1756c73-6bc7-44c5-8082-9afaa956e4f4.png)

**Specially this thing** 
![2022-11-15-16:02:28](https://user-images.githubusercontent.com/55500372/201926286-594634d5-f3c7-43b9-b23e-9aea1cef2719.png)

**Comment by siduck** [comment]
do you have tsx and typescript tsparsers installed?

**Comment by Tinkerbells** [comment]
Do you mean treesitter parser. If so, yes I have typescript parser installed

**Comment by Tinkerbells** [comment]
I'm sorry just installed tsx parser and everything looks fine. But how I can do this automatically when reinstall config for example?

**Comment by siduck** [comment]
@Tinkerbells take a look at our example_config repo, all you need to do is override treesitter's config section ( the ensure_installed table ) i hope you know how to do that.
