### ISSUE TITLE
add nvim-tundra theme

### ISSUE THREAD

**Issue by denis631** [NvChad/base46#143]
Nvim-tundra is a popular nvim theme and having it in NvChad would be awesome.
nvim-tundra [link](https://github.com/sam4llis/nvim-tundra)

**Comment by siduck** [comment]
i will port that theme this friday

**Comment by siduck** [comment]
@denis631 its in the dev branch

![image](https://user-images.githubusercontent.com/59060246/205629627-f7308d6d-9451-402f-ad8e-b98cba009e6b.png)


in order to use dev branch of base46, you have to use dev branch of nvchad
