### ISSUE TITLE
Lack of highlight group in diff mode

### ISSUE THREAD

**Issue by kaonashihirota** [NvChad/base46#144]
Enter diff mode
``` bash
 nvim -d a.md b.md
```
The result
![image](https://user-images.githubusercontent.com/47310453/203711234-3919fa35-7fdf-4044-89cf-883a7769ed70.png)

**Comment by kaonashihirota** [comment]
There is a theme plugin that might provide some clues about the issue.
[https://github.com/shaunsingh/nord.nvim/blob/993a69aad81c5d82106e1a7dc553136c33c1cabe/lua/nord/theme.lua#L220](url)

**Comment by siduck** [comment]
@kahirota the link doesnt work
