### ISSUE TITLE
add Aurora theme

### ISSUE THREAD

**Issue by bryant-the-coder** [NvChad/base46#145]
https://github.com/ray-x/aurora

**Comment by siduck** [comment]
i will port that theme this saturday

**Comment by siduck** [comment]
yo @bryant-the-coder i just saw that the theme explicitly styles many languages too so i cant port it

**Comment by bryant-the-coder** [comment]
> yo @bryant-the-coder i just saw that the theme explicitly styles many languages too so i cant port it

Heyyo. Its ok! Thanks though
