### ISSUE TITLE
Disable syntax error highlight

### ISSUE THREAD

**Issue by h4r1337** [NvChad/base46#146]
There is a red highlight above the code when there's a syntax error. It happens as we type... before even completing the code and it's annoying.
Is there any way to disable this highlight feature?
![image](https://user-images.githubusercontent.com/72344536/203348167-cb6f0cdd-daea-427d-9dda-a634c2aa36ac.png)

**Comment by siduck** [comment]
unable to produce and not much info provided so closing this
