### ISSUE TITLE
Handle CursorLine background using cursorline/nocursorline instead of highlights

### ISSUE THREAD

**Issue by dgmora** [NvChad/base46#154]
The CursorLine background is set to `base00`, which makes the cursor line not visible:

![Screenshot 2022-12-27 at 11 24 26](https://user-images.githubusercontent.com/3609616/209652625-327fac85-de76-47c5-8e95-723ef01a4e13.png)

To overwrite this, I set the bg to `one_bg`:
```lua
  hl_override = {
    CursorLine = {
       bg = "one_bg",
    },
  },
```
![Screenshot 2022-12-27 at 11 23 40](https://user-images.githubusercontent.com/3609616/209652642-b56db6bc-3abb-4829-a1a2-d1785881f091.png)

The usual way way to enable/disable this is to set the option `cursorline` or `nocursorline`, then there's no need to change highlight groups. 

To keep the same behaviour with this new highlight you would just need to set `nocursorline`

**Comment by siduck** [comment]
yo @dgmora that is intentional, i wanted the cursorline to be hidden by default, Also i cant disable cursorline entirely because i want the current line number to be highlighted!
