### ISSUE TITLE
monochrome theme

### ISSUE THREAD

**Issue by siduck** [NvChad/base46#155]

**Comment by ghost** [comment]
so how many monochrome themes to make.. like how many colors

**Comment by siduck** [comment]
@sontaimnt i think i didnt word it well, this theme will have 2 main colors , fg and bg . rest of the colors will be derived from both the colors

**Comment by ghost** [comment]
monochrome is that cool retro terminal like stuff right??

**Comment by ghost** [comment]
@siduck  monochrome usually means 4 colors a grey , black , white , main

and to optimise to nvchad using a hex coloring tool we need to make 32 colors for it

**Comment by siduck** [comment]
> monochrome is that cool retro terminal like stuff right??



> monochrome is that cool retro terminal like stuff right??

idk, what i want is to derive all colors from fg/bg color so basically different shades of fg/bg. Not sure if this is monochrome

**Comment by ghost** [comment]
monochrome is those 80s like crt monitors theme.. i will try to make an attempt to do it..

**Comment by siduck** [comment]
> monochrome is those 80s like crt monitors theme.. i will try to make an attempt to do it..

no i will make this one!

EDIT : we already have it lul
