### ISSUE TITLE
nvim-treesitter-html: “invisible” s tag entered text

### ISSUE THREAD

**Issue by niczapata** [NvChad/base46#161]
@siduck I show you this issue so that you take it into account for version 0.2 of NvChad.

![image](https://user-images.githubusercontent.com/35777697/220396632-4ac08f1e-d4a9-4e3e-bf60-4f02f1d231e7.png)

Happens with the nvim-treesitter-html plugin (in default highlight works fine), text entered in the <s></s> tag is made “invisible”, happens in both light and dark Base46 themes.

Best regards.

**Comment by siduck** [comment]
@NicolasZapata thanks for reporting, I have made the change in the v2.0 branch of base46. 

for now just override the hl group like this 

```lua
M.ui = {
  hl_override = {
    ["@text.strike"] = {
      fg = "white",
    },
  },
}
```

**Comment by niczapata** [comment]
Thank you, @siduck 😄👍
