### ISSUE TITLE
theme not working correctly

### ISSUE THREAD

**Issue by Aneeqasif** [NvChad/base46#171]
**Describe the bug**
after i change the theme the currentline is still using the previous colors

**To Reproduce**
1. change the theme through leader th

**Expected behavior**
full theme change

**Screenshots**
![image](https://user-images.githubusercontent.com/78728701/225985723-2ef38e2b-7421-4fd9-b987-22f10a0370b6.png)
**Desktop (please complete the following information):**
 - Operating System arco 
 - Terminal alacritty / wezterm
 - Version of Neovim v0.8.3

**Comment by siduck** [comment]
seems like user define highlights or overriden highlights dont seem to reload

**Comment by Aneeqasif** [comment]
> 

i havent done any customizations , just installed it , and its behaving like this

**Comment by siduck** [comment]
go to chadrc and save the file again

**Comment by Aneeqasif** [comment]
> go to chadrc and save the file again

so i tried it many times it didnt worked
removeing following line seems to solve the issue 
```lua
 hl_override = highlights.override,

```

**Comment by siduck** [comment]
it doesnt actually solve the issue. that file contains overrides for highlight groups. and the one shown in the image is CursorLine highlight group. this is an actual bug, will try to fix it tomorrow

**Comment by Aneeqasif** [comment]
> it doesnt actually solve the issue. that file contains overrides for highlight groups. and the one shown in the image is CursorLine highlight group. this is an actual bug, will try to fix it tomorrow

right thanks for ur time , one other thing that i wanna ask that , i am using https://github.com/wfxr/minimap.vim this plugin for minimap but i am confused how can i make its colors consistent and reasonable with applied colorscheme , this plugin has it own highlight groups and i dont know how can  i set them properly in highlights.lua , any help?

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/226153734-3fac009d-ea11-4903-9e1e-dbdca3a9cc20.png)

override its highlight groups , read this part https://nvchad.com/docs/config/theming

**Comment by Aneeqasif** [comment]
i am not experienced user i need some help how to convert the vim script version to lua

**Comment by siduck** [comment]
@Aneeqasif did you add that highlight group first? read our docs please

**Comment by Aneeqasif** [comment]
yeah i have read that , there is no specific instruction related to that

**Comment by siduck** [comment]
> yeah i have read that , there is no specific instruction related to that

there is, hl_add option. read docs properly
