### ISSUE TITLE
`guisp` color is substitute incorrectly

### ISSUE THREAD

**Issue by lucario387** [NvChad/base46#172]
@siduck Have a hlgroup with 
```lua
{
  bg = "light_grey", fg = "white", sp = "light_grey"
}
```

Expected: Color loads correctly

Actual: 
![image](https://user-images.githubusercontent.com/29790821/226290120-6b691de1-82b0-42c1-89d9-6ca2e82136f5.png)

**Comment by siduck** [comment]
Check base46/init.lua line 33, on phone rn so can't commit

**Comment by lucario387** [comment]
probably a different issue then, there's 2 bugs with that
