### ISSUE TITLE
Highlights not being applied

### ISSUE THREAD

**Issue by mikededo** [NvChad/base46#182]
**Describe the bug**

I have defined custom highlights and after a recent update they have stopped being applied. Also, when opening a file, it is partially rendered with the expected highlights but after they are changed. I have not been able to determine when does that happen (I guess when the computer is more busy, as it takes more time to apply highlights).

**To Reproduce**

Here is my [`chadrc.lua`](https://github.com/mikededo/.dotfiles/blob/main/nvim/.config/nvim/lua/custom/chadrc.lua) and my [`highlights.lua`](https://github.com/mikededo/.dotfiles/blob/main/nvim/.config/nvim/lua/custom/highlights.lua)

**Expected behavior**

To see the customized highlights.

**Desktop (please complete the following information):**

 - Operating System: MacOS 13.3.1
 - Terminal: Kitty
 - Version of Neovim: 0.9.0

**Comment by siduck** [comment]
TS* highlight groups are removed btw, treesitter now uses "@constant" etc

**Comment by mikededo** [comment]
Ah, I will take a look into it.

**Comment by mikededo** [comment]
I can't get it working.

This is what I can see in the telescope preview, which has the expected colors:

<img width="1505" alt="image" src="https://user-images.githubusercontent.com/48334745/232559274-f1152f8e-46a7-420a-b3c3-7d557393d828.png">

However, when opening the file colors are not correct:

<img width="588" alt="image" src="https://user-images.githubusercontent.com/48334745/232559597-9e22ac0d-7625-402d-8452-a0f87db374c4.png">

Any ideas?

**Comment by mikededo** [comment]
It seems related with LSP. Once it finishes loading, it updates the colors. I have checked it by running `LspRestart`. Colors are correct but when finished it changes back to incorrect.

**Comment by siduck** [comment]
hi @mikededo  did you update semantic tokens in chadrc? also did u update nvchad to the latest and all plugins too?

**Comment by chikko80** [comment]
@siduck

I have lsp overrides in my highlights.lua. They completely stopped working. How can i fix this? I don't really get the idea why they are now linked to Treesitter groups

```lua
---@type Base46HLGroupsList
M.override = {
  ["@lsp.type.method"] = { fg = "#61AFEF" },
  ["@lsp.type.decorator"] = { fg = "#61AFEF" },
  ["@lsp.type.variable"] = { fg = "#B1B8C4" },
  ["@lsp.type.parameter"] = { fg = "#D19A66" },
  ["@lsp.type.struct"] = { fg = "#E5C07B" },
  ["@lsp.type.namespace"] = { fg = "#E5C07B" },
  ["@lsp.type.property"] = { fg = "#D5B3FF" },
  ["@lsp.type.enumMember"] = { fg = "#56B6C2" },
  ["@lsp.type.interface"] = { fg = "#2ACFAB" },
  ["@lsp.type.macro"] = { fg = "#D19A66" },
}
```

**Comment by siduck** [comment]
@chikko80  check default_config.lua file, there's an option for semantic tokens, enable that in chadrc

**Comment by chikko80** [comment]
@siduck  i have that enabled. You added this option at 10th april.
But since 12th of april, or as soon as i update base46 plugin, the colors doesn't work anymore

**Comment by siduck** [comment]
> @siduck  i have that enabled. You added this option at 10th april.
> But since 12th of april, or as soon as i update base46 plugin, the colors doesn't work anymore

Ok add this to each of your hl groups , link="",

**Comment by mikededo** [comment]
In my case, I have everything up to date, NvChad and plugins.

**Comment by chikko80** [comment]
> > @siduck  i have that enabled. You added this option at 10th april.
> > But since 12th of april, or as soon as i update base46 plugin, the colors doesn't work anymore
> 
> Ok add this to each of your hl groups , link="",

Works after clearing cache

**Comment by mikededo** [comment]
@chikko80, `rm -rf ~/.cache/nvim`? I will try that and reinstall the plugins. But it is kind of strange.

**Comment by mikededo** [comment]
Issue not solved, in my case:

<img width="1383" alt="image" src="https://user-images.githubusercontent.com/48334745/232698991-7745fcba-8bd2-48f8-99d2-6cad67d96b61.png">

As you can see at the top-left of the image, there's the `export class...` all in purple, when it should be a mix, as the class should be yellow, as in the telescope preview.

**Comment by mikededo** [comment]
My TS highlights are the following, I looked for them and updated yesterday, hoping it would work:

```lua
return {
  Normal = { fg = '#ABB2BF', bg = 'black' },
  StatusLineNC = { fg = '#ABB2BF' },
  DashboardCenter = { fg = '#ABB2BF' },
  DashboardFooter = { fg = '#ABB2BF' },
  DashboardHeader = { fg = '#ABB2BF' },
  DashboardShortcut = { fg = '#ABB2BF' },
  IndentBlanklineChar = { fg = '#3F4854' },
  Delimiter = { fg = '#ABB2BF' },
  ['@punctuation.delimiter'] = { fg = '#ABB2BF' },
  ['@punctuation.bracket'] = { fg = '#ABB2BF' },
  ['@punctuation.special'] = { fg = '#ABB2BF' },
  ['@attribute'] = { fg = '#E06C75' },
  ['@field'] = { fg = '#E06C75' },
  ['@symbol'] = { fg = '#E5C07B' },
  ['@namespaces'] = { fg = '#E5C07B' },
  ['@property'] = { fg = '#E06C75' },
  ['@constant'] = { fg = '#D19A66' },
  ['@tag.attribute'] = { fg = '#E5C07B' },
}
```

Any idea or other thing I could try?

**Comment by chikko80** [comment]
@mikededo 

```
rm -rf ~/.local/share/nvim
rm -rf ~/.local/state/nvim
```

**Comment by mikededo** [comment]
I did run `rm -rf ~/.local/share/nvim ~/.cache/nvim`, reinstalled everything and the problem persists 😞

**Comment by siduck** [comment]
@mikededo  add `link = ""` to all of your highlight groups which are related to syntax, like treesitter etc

**Comment by alexstrassheim** [comment]
I think I have the same problem.
When I put the highlights inside 'chadrc.lua' they work, but when I move them to 'highlights.lua' the colors don't work anymore either. I also tried it with `link = ""` to my highlight groups, but also without success. 
`lsp_semantic_tokens = true` is also active 🤔.
![Screenshot 2023-04-18 at 10 10 22](https://user-images.githubusercontent.com/335507/232720608-1f1a6f54-b711-49b9-9305-7f6024e1e784.png)

**Comment by siduck** [comment]
> I think I have the same problem. When I put the highlights inside 'chadrc.lua' they work, but when I move them to 'highlights.lua' the colors don't work anymore either. I also tried it with `link = ""` to my highlight groups, but also without success. `lsp_semantic_tokens = true` is also active thinking. ![Screenshot 2023-04-18 at 10 10 22](https://user-images.githubusercontent.com/335507/232720608-1f1a6f54-b711-49b9-9305-7f6024e1e784.png)

are you using windows by any chance?

**Comment by mikededo** [comment]
Not me

**Comment by alexstrassheim** [comment]
> are you using windows by any chance?

Also not me

- macOS 13.3.1
- Terminal: Alacritty 0.12.0
- NVIM v0.9.0

**Comment by siduck** [comment]
@mikededo  link="" for your syntax related hl groups

**Comment by mikededo** [comment]
Doesn't solve the issue 😢

**Comment by siduck** [comment]
:/ 

i'll try it tonight

**Comment by siduck** [comment]
@mikededo  is nvchad uptodate?

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/233848073-53257c8a-fd42-4beb-9087-e5da6bb7d9f8.mp4

@mikededo  unable to reproduce the error at all. Please make sure you had uptodate nvchad and other plugins

**Comment by alexstrassheim** [comment]
@siduck I probably had a typo at some point. The highlights work for me now too. Thanks for your support 👍

**Comment by mikededo** [comment]
@siduck I have everything up to date, I will look into it. Have you tried with the `tsserver`? It is what I normally work with and breaks.

**Comment by siduck** [comment]
> @siduck I have everything up to date, I will look into it. Have you tried with the `tsserver`? It is what I normally work with and breaks.

Please make sure you have semantic stuff not enabled

**Comment by mikededo** [comment]
How can I validate that?

**Comment by siduck** [comment]
> How can I validate that?

show core/default.config.lua and your chadrc

**Comment by mikededo** [comment]
I don't have a `core/default.confg.lua`.

The `.chadrc` is:

```lua
local M = {}

-- local ui = require('NvChad/ui.nvim')

-- Theme and colors
M.ui = {
  theme = 'onedommed',
  transparency = false,
  hl_override = require('custom.highlights'),
  nvdash = {
    load_on_startup = true,
    header = {
      '⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣠⣤⣤⣴⣦⣤⣤⣄⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ ',
      '⠀⠀⠀⠀⠀⠀⢀⣤⣾⣿⣿⣿⣿⠿⠿⠿⠿⣿⣿⣿⣿⣶⣤⡀⠀⠀⠀⠀⠀⠀ ',
      '⠀⠀⠀⠀⣠⣾⣿⣿⡿⠛⠉⠀⠀⠀⠀⠀⠀⠀⠀⠉⠛⢿⣿⣿⣶⡀⠀⠀⠀⠀ ',
      '⠀⠀⠀⣴⣿⣿⠟⠁⠀⠀⠀⣶⣶⣶⣶⡆⠀⠀⠀⠀⠀⠀⠈⠻⣿⣿⣦⠀⠀⠀ ',
      '⠀⠀⣼⣿⣿⠋⠀⠀⠀⠀⠀⠛⠛⢻⣿⣿⡀⠀⠀⠀⠀⠀⠀⠀⠙⣿⣿⣧⠀⠀ ',
      '⠀⢸⣿⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠸⣿⣿⡇⠀ ',
      '⠀⣿⣿⡿⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣇⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⠀ ',
      '⠀⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⢠⣿⣿⡟⢹⣿⣿⡆⠀⠀⠀⠀⠀⠀⠀⣹⣿⣿⠀ ',
      '⠀⣿⣿⣷⠀⠀⠀⠀⠀⠀⣰⣿⣿⠏⠀⠀⢻⣿⣿⡄⠀⠀⠀⠀⠀⠀⣿⣿⡿⠀ ',
      '⠀⢸⣿⣿⡆⠀⠀⠀⠀⣴⣿⡿⠃⠀⠀⠀⠈⢿⣿⣷⣤⣤⡆⠀⠀⣰⣿⣿⠇⠀ ',
      '⠀⠀⢻⣿⣿⣄⠀⠀⠾⠿⠿⠁⠀⠀⠀⠀⠀⠘⣿⣿⡿⠿⠛⠀⣰⣿⣿⡟⠀⠀ ',
      '⠀⠀⠀⠻⣿⣿⣧⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣿⠏⠀⠀⠀ ',
      '⠀⠀⠀⠀⠈⠻⣿⣿⣷⣤⣄⡀⠀⠀⠀⠀⠀⠀⢀⣠⣴⣾⣿⣿⠟⠁⠀⠀⠀⠀ ',
      '⠀⠀⠀⠀⠀⠀⠈⠛⠿⣿⣿⣿⣿⣿⣶⣶⣿⣿⣿⣿⣿⠿⠋⠁⠀⠀⠀⠀⠀⠀ ',
      '⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠉⠛⠛⠛⠛⠛⠛⠉⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ ',
    },
  },
  cmp = {
    style = 'flat_dark',
    selected_item_bg = 'colored',
  },
  statusline = require('custom.configs.statusline'),
}

M.plugins = 'custom.plugins'

return M
```

**Comment by siduck** [comment]
lua/core/default_config.lu @mikededo

**Comment by mikededo** [comment]
```lua
local M = {}

M.options = {
  nvchad_branch = "v2.0",
}

M.ui = {
  ------------------------------- base46 -------------------------------------
  -- hl = highlights
  hl_add = {},
  hl_override = {},
  changed_themes = {},
  theme_toggle = { "onedark", "one_light" },
  theme = "onedark", -- default theme
  transparency = false,
  lsp_semantic_tokens = false, -- needs nvim v0.9, just adds highlight groups for lsp semantic tokens

  -- https://github.com/NvChad/base46/tree/v2.0/lua/base46/extended_integrations
  extended_integrations = {}, -- these aren't compiled by default, ex: "alpha", "notify"

  -- cmp themeing
  cmp = {
    icons = true,
    lspkind_text = true,
    style = "default", -- default/flat_light/flat_dark/atom/atom_colored
    border_color = "grey_fg", -- only applicable for "default" style, use color names from base30 variables
    selected_item_bg = "colored", -- colored / simple
  },

  telescope = { style = "borderless" }, -- borderless / bordered

  ------------------------------- nvchad_ui modules -----------------------------
  statusline = {
    theme = "default", -- default/vscode/vscode_colored/minimal
    -- default/round/block/arrow separators work only for default statusline theme
    -- round and block will work for minimal theme only
    separator_style = "default",
    overriden_modules = nil,
  },

  -- lazyload it when there are 1+ buffers
  tabufline = {
    show_numbers = false,
    enabled = true,
    lazyload = true,
    overriden_modules = nil,
  },

  -- nvdash (dashboard)
  nvdash = {
    load_on_startup = false,

    header = {
      "           ▄ ▄                   ",
      "       ▄   ▄▄▄     ▄ ▄▄▄ ▄ ▄     ",
      "       █ ▄ █▄█ ▄▄▄ █ █▄█ █ █     ",
      "    ▄▄ █▄█▄▄▄█ █▄█▄█▄▄█▄▄█ █     ",
      "  ▄ █▄▄█ ▄ ▄▄ ▄█ ▄▄▄▄▄▄▄▄▄▄▄▄▄▄  ",
      "  █▄▄▄▄ ▄▄▄ █ ▄ ▄▄▄ ▄ ▄▄▄ ▄ ▄ █ ▄",
      "▄ █ █▄█ █▄█ █ █ █▄█ █ █▄█ ▄▄▄ █ █",
      "█▄█ ▄ █▄▄█▄▄█ █ ▄▄█ █ ▄ █ █▄█▄█ █",
      "    █▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█ █▄█▄▄▄█    ",
    },

    buttons = {
      { "  Find File", "Spc f f", "Telescope find_files" },
      { "  Recent Files", "Spc f o", "Telescope oldfiles" },
      { "  Find Word", "Spc f w", "Telescope live_grep" },
      { "  Bookmarks", "Spc b m", "Telescope marks" },
      { "  Themes", "Spc t h", "Telescope themes" },
      { "  Mappings", "Spc c h", "NvCheatsheet" },
    },
  },

  cheatsheet = { theme = "grid" }, -- simple/grid

  lsp = {
    -- show function signatures i.e args as you type
    signature = {
      disabled = false,
      silent = true, -- silences 'no signature help available' message from appearing
    },
  },
}

M.plugins = "" -- path i.e "custom.plugins", so make custom/plugins.lua file

M.lazy_nvim = require "plugins.configs.lazy_nvim" -- config for lazy.nvim startup options

M.mappings = {}

return M
```

I guess it is the default, as I haven't touched anything.

**Comment by siduck** [comment]
hmmm idk then, i cant produce your issue :(

**Comment by mikededo** [comment]
No worries, I will dig into it when I have more time! Thanks anyway

**Comment by siduck** [comment]
@mikededo try the example_config as your custom dir and add your hl_override there

just tried with a minimal chadrc, and it works

look https://0x0.st/HK9-.mp4

**Comment by mikededo** [comment]
Finally solved the issue. When you said it had to be something regarding lsp highlights, I was quite certain it had to be because of that, as the configs were ok. I found this reddit post: https://www.reddit.com/r/neovim/comments/109vgtl/how_to_disable_highlight_from_lsp/

Adding this line to the `on_attach` function:

```lua
local on_attach = function(client, bufnr)
  client.server_capabilities.semanticTokensProvider = nil -- <- Disable LSP tokens
  -- ...
en
```

**Comment by siduck** [comment]
> Reference i

btw we already had that!!

![image](https://user-images.githubusercontent.com/59060246/234888801-21bc6af5-5da9-4eaf-9319-e1c919511d2d.png)
