### ISSUE TITLE
Reload options on the fly while editing chadrc.lua only works depending how you open it

### ISSUE THREAD

**Issue by Thanatermesis** [NvChad/base46#183]
Reading the documentation I was trying to see the "changes on the fly" when editing the "chadrc.lua" file but it didn't worked, after many tries I noticed that only works when I used to open it manually as:

> :e ~/.config/nvim/lua/custom/chadrc.lua

But if try to open nvim editing the file, it doesn't work:

> nvim ~/.config/nvim/lua/custom/chadrc.lua

Same issue if I try to open it from the dashboard "recent files", it only works with the :e mode

**Comment by Thanatermesis** [comment]
After spending hours trying to reproduce the issue in another machine where I was unable to make it working, I finally found it seems to work when I use:

> :e ~/.config/nvim/lua/custom/chadrc.lua

But it **doesn't work** when I use (running from the home dir):

> :e .config/nvim/lua/custom/chadrc.lua

So seems like the issue has relation with the **absolute path**, maybe nvim or nvchad doesn't understand it correctly when it is not given

**Comment by Thanatermesis** [comment]
__**Important**: previous comment updated__

It works editing the file with ":e" (from inside nvim) but not calling nvim to edit the file as "nvim ~/.conf..."

To make it working, you need to follow these steps:
* run "nvim" alone
* then edit the file using ":e" and including absolute path (important)
* modify / save the file, to get the reload options on the fly

**Comment by siduck** [comment]
i usually open files via telescope or nvimtree, never faced this issue! Will investigate at this weekend

**Comment by Thanatermesis** [comment]
If im not wrong it happens too opening them from telescope, try a clean install which I seen that the issue always happen, unless doing the previously noted steps, which works, but in multiple ways it doesn't

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/233847970-026440ca-1af0-45c2-8845-b9bd9ddafcc6.mp4

cannot reproduce,  make a video like I did!

**Comment by Thanatermesis** [comment]
That's strange, I cannot reproduce it now anymore in a new clean install like i did before 🤔 so I will close the issue for now
