### ISSUE TITLE
Not all highlights can be defined on the theme

### ISSUE THREAD

**Issue by Thanatermesis** [NvChad/base46#189]
I'm trying to create a theme, where I don't want the folded blocks having a background color, so I added:

```lua
M.polish_hl = {
  ["@Folded"] = { bg = M.base_16.base00 },
end
```

I can add other entries but this one has no effect, seems like in the file base46/init.lua is overwited by the definitions in ```base46/integrations/defaults.lua```, since this depends on the theme look, how I can add the highlight on the theme and not in the user conf?

Maybe could be good to have an extra block, like:

```lua
M.theme_hl = {
  ...
```

**Comment by siduck** [comment]
@Thanatermesis make sure Folded highlight is there in our default list of highlight groups, if not then polish_hl is useless there

**Comment by Thanatermesis** [comment]
This means that if I want to add a new highlight in the theme is not possible? 

For example I want to define "diffNewFile" and "diffOldFile" which is the syntax for the file when editing a .diff file

**Comment by siduck** [comment]
> This means that if I want to add a new highlight in the theme is not possible?
> 
> For example I want to define "diffNewFile" and "diffOldFile" which is the syntax for the file when editing a .diff file

it is possible if you add it in chadrc's hl_add field! or else I'll add the Folded hl groups for you in base46

**Comment by Thanatermesis** [comment]
Hi @siduck , the Folded hl was already included in the default list :) seems like I wrongly used the @ character for it, I was now wondering how to set some HL values that doesn't exist (so, hl_add), the only way is adding them in the default.lua file or it can be done in the theme? for example for those diffNewFile or diffOldFile (when editing a .diff file)

**Comment by siduck** [comment]
you can include diffnewFile in our integration file, git is the file name. check it

**Comment by Thanatermesis** [comment]
Mmmh, I'm not sure to understood, what is the integration file I should add it? base46/integrations/git.lua ? but then is not possible to add highlights not defined in a theme file? 🤔

BTW Im just sending you a pull request for .diff files
