### ISSUE TITLE
Python f-string highlighting is broken exclusively only in NvChad

### ISSUE THREAD

**Issue by simon-liebehenschel** [NvChad/base46#196]
Based on https://github.com/NvChad/NvChad/discussions/2021 I believe this is the right place to report the issue.

## Valid highlighting. 

Similar highlighting is in LunarVim, VSCode, PyCharm, etc. Basically, even plain LazyVim setup show f-strings well out of the box.

![f-string](https://github.com/NvChad/base46/assets/70140627/d3c4b93a-8b8a-4dec-9d78-4ef169ce9186)

## NvChad invalid highlighting

![f-string_nvchad](https://github.com/NvChad/base46/assets/70140627/11f39cb2-f347-43b5-bc54-22f4b9f98897)

## Explanation

A variable inside a f-string must have a different color.

## Steps to reproduce

- Install NvChad.
- `:MasonInstall pyright`
- create `pyrightconfig.json` in the project root with the following text:
    ```json
    {
      "venvPath": "."
    }
    ```
    (I use this config because my ".venv" is in the project root)
- open any `*.py` file

I have a Dockerfile but I think it is redundant here. Let me know if you will need a reproducible environment, I will share the Dockerfile then.

**Comment by siduck** [comment]
![image](https://github.com/NvChad/base46/assets/59060246/f412749c-269c-43d4-bd4b-9c7896d14fc5)

TSInstall python
