### ISSUE TITLE
I believe a tokyolight and jetbrains darcula theme will be a great change!

### ISSUE THREAD

**Issue by Upsurge-11** [NvChad/base46#201]
[https://github.com/folke/tokyonight.nvim](TokyoNight)
[https://github.com/doums/darcula](Darcula)

**Comment by siduck** [comment]
@Upsurge-11  those are already there. check chadracula and tokyonight in your theme swicher

**Comment by Upsurge-11** [comment]
@siduck Tokyonight light isn't there .. although dark is present.
Also darcula is different from dracula.
Darcula is the colorscheme u find in jetbrains ide usually.

**Comment by siduck** [comment]
oops i misread

**Comment by cuongn265** [comment]
do you guys think a generator will be a game changer?

**Comment by siduck** [comment]
> do you guys think a generator will be a game changer?

how do you want the generator to be?
