### ISSUE TITLE
Supported hex colors

### ISSUE THREAD

**Issue by wobbleRed** [NvChad/base46#205]
I have been trying to customize the colors for viewing my git diffs and I keep getting the following:
`Invalid highlight color: <color hex val>`
Here is the hl_override object from my chadrc file:
Some of the values work and others dont. Im using values from the following page: https://www.ditig.com/256-colors-cheat-sheet

Is there a list of supported values I need to choose from? I have also tried using hex values from themes inside this repo and I still get errors. Please advise. 🙏 

```
hl_override = {
    DiffAdd = {
      fg = "#008000",
      bg = "#00d700"
    },

    DiffAdded = {
      fg = "green",
    },

    DiffChange = {
      fg = "#000080",
      bg = "#9bdead",
      ctermfg = "#ff00ff",
      ctermbg = "#EACD61"
    },

    DiffChangeDelete = {
      fg = "#ff0000",
    },

    DiffModified = {
      fg = "#d7ff00",
    },

    DiffDelete = {
      fg = "#ff0000",
      bg = "#ffffff"
    },

    DiffRemoved = {
      fg = "#ff0000",
    },
 },
```

**Comment by wobbleRed** [comment]
After doing a bit more digging I can see that its not the hex value but the ctermfg and ctermbg. I guess they are not supported. Is there any known work around? It would be really nice to have my diff tool work. 😬

**Comment by siduck** [comment]
@wobbleRed  cterm colors dont support hex colors, thats why there are guifg/bg which are now bg/fg in nvim_hl function
