### ISSUE TITLE
Toggle theme missing some colors from dark to light theme

### ISSUE THREAD

**Issue by fabiodcorreia** [NvChad/base46#206]
I created 2 themes under custom/themes/ as described on the documentation (catppuccin_frappe.lua and catppuccin_latte.lua) and I set both on chadrc.lua. And it works fine.

One thing that I noticed is that if toggle the theme from light to dark and back again to light some of the colors remain from the dark theme or get lost. For instance the status line filename and git brand and the buffer name on the tabs.

Light theme with correct colors:
<img width="1012" alt="image" src="https://github.com/NvChad/base46/assets/4386521/2e217681-2239-4b15-8659-854dc35d1cf2">
<img width="362" alt="image" src="https://github.com/NvChad/base46/assets/4386521/6373a54e-028e-42f9-9ad2-4d358edf1a95">

After I switch to dark

<img width="1016" alt="image" src="https://github.com/NvChad/base46/assets/4386521/7831243a-0098-417f-81af-e5ec7c75c78c">
<img width="356" alt="image" src="https://github.com/NvChad/base46/assets/4386521/8c1b57dd-59ab-4211-b07d-51718793b59b">

Switching back to light

<img width="1025" alt="image" src="https://github.com/NvChad/base46/assets/4386521/b1284c62-fa03-4138-bceb-7565d179b9c2">
<img width="360" alt="image" src="https://github.com/NvChad/base46/assets/4386521/12c32773-5b60-416a-a0ad-6ba1e519d305">

Switching back o dark its all good but if I switch back to light again now the colors are the ones from dark theme.

<img width="1022" alt="image" src="https://github.com/NvChad/base46/assets/4386521/b44154ff-346b-4774-985f-7a52244c02b0">
<img width="361" alt="image" src="https://github.com/NvChad/base46/assets/4386521/741569cd-1513-4cd1-a6fc-7442537ab8a7">

After this points I can toggle as many times as I want and the result is always wrong. I need to exit nvim open again a toggle the themes one to fix.

For some reason this only happens on the light theme, the dark is always good regardless how many combinations I do.

The themes can be found at the following links:
- https://gist.github.com/fabiodcorreia/032f87acad34ed779cfbeb5fde199336
- https://gist.github.com/fabiodcorreia/c5dc5bdb7567b1a6ccd7eeb4c715fef2

**Comment by antoineco** [comment]
`lightbg` is commented.

**Comment by fabiodcorreia** [comment]
> `lightbg` is commented.

It's not used by the vscode_colored theme that I use. Anyway I tried with that uncommented and the result is the same.

**Comment by antoineco** [comment]
Found yesterday on Discord. The culprit is here:

https://github.com/NvChad/base46/blob/bad87b034430b0241d03868c3802c2f1a4e0b4be/lua/base46/integrations/statusline.lua#L9-L15

**Comment by fabiodcorreia** [comment]
I changed my local copy and I think this fix the problem but I don't if it's the best solution since I don't know much about lua.

```lua
local light_grey = colors.light_grey
local statusline_bg = colors.statusline_bg

if statusline_theme == "vscode" then
  statusline_bg = generate_color(colors.statusline_bg, 1)
  light_grey = generate_color(colors.light_grey, 20)
elseif statusline_theme == "vscode_colored" then
  statusline_bg = generate_color(colors.statusline_bg, 1)
  light_grey = generate_color(colors.light_grey, 25)
end
```

So I created 2 local variables to hold the lighter version of the color instead of setting it on the colors variable. After that I replace all the call of colors.statusline_bg and colors.light_grey with the local variable. I tried several times and replicate the issue but I can't reproduce it anymore.

**Comment by RichterMaximilian** [comment]
I still have the problem even after the fix.

I use the `one_light` theme and the `vscode_colored` statusline. After toggling the theme back and forth, the file name and git brand don't change its color back to the light theme.

It is fixed for the tabs though.

**Comment by siduck** [comment]
@fabiodcorreia

**Comment by fabiodcorreia** [comment]
@siduck I think the issue is with the themes, for example the issue appears for onedark and one_light but for everforest and everforest_light it works fine, GitHub Light and Dark also doesn't work but Grovbox looks good.

**Comment by siduck** [comment]
https://github.com/NvChad/base46/commit/66d1fb4c28500a4e6ad8a0fefcec62302b97ceab
