### ISSUE TITLE
Request: storm variant of tokyo night

### ISSUE THREAD

**Issue by mblarsen** [NvChad/base46#207]
Request from Discord:

@mblarsen: Can one make requests for themes here? You already have the awesome tokyo night theme. Would it be a big ask if you could add the "storm" variant if it too?

@siduck : seems fine to me, make an issue on base46 repo

**Comment by chrsolr** [comment]
+1

**Comment by siduck** [comment]
hmmm wait, there doesnt seem to b e much difference between both, besides the bg color,  right?

**Comment by ItsTerm1n4l** [comment]
yes, background colour is the only difference

**Comment by siduck** [comment]
just override color of Normal hlgroup then
