### ISSUE TITLE
Italics Support not working in Elixir Files

### ISSUE THREAD

**Issue by blackode** [NvChad/base46#209]
**Describe the bug**
Italics for Function and Keyword are not working.

**Expected behavior**
Keywords in elixir language files are to be  italic.

**Screenshots**
![image](https://github.com/NvChad/NvChad/assets/9107477/43f94799-6fd0-460d-a50f-8f16bac2efef)

**Desktop (please complete the following information):**
 - Operating System - Ubuntue 22.04
 - Terminal - Kitty
 - Version of Neovim - NVIM v0.10.0-dev-203+geb4676c67

**Comment by kayuxx** [comment]
@blackode try this, its should work for you
```lua
-- custom/highlight
M.override = {
 Keyword = { link = "@keyword.ex" }
}
M.add = {
 ["@keyword.ex"] = { italic = true }
}
```

**Comment by blackode** [comment]
@kayuxcodes 
I have tried :point_up: config still same no effect.
Please Check the following screenshot
![image](https://github.com/NvChad/base46/assets/9107477/e56b85a3-2dae-4a3c-8032-19415b51627e)

**Comment by kayuxx** [comment]
@blackode in your elixir file run this command and tell me if there is an effect `:hi @keyword.ex guibg=black guifg=white`

**Comment by blackode** [comment]
@kayuxcodes 
Nothing changed in the file 
![image](https://github.com/NvChad/base46/assets/9107477/66fa671d-4763-48d6-9ddb-20a0987b89cb)

When I run just `:hi @keyword.ex``  It shows the following output.

`````
:hi @keyword.ex                                                                                                                                      
@keyword.ex    xxx cterm=italic gui=italic guifg=White guibg=Black
`

**Comment by kayuxx** [comment]
@blackode its already applied, maybe your terminal has issue or your font doesn't support italic.

**Comment by siduck** [comment]
```lua
M.add = {
 ["@keyword.elixir"] = { italic = true }
}
```

its not ex because elixir is the filetype, always check filetype name by `set ft` command
