### ISSUE TITLE
Is it possible to separate the plugin from NvChad?

### ISSUE THREAD

**Issue by LexeyKhom** [NvChad/base46#210]
I wanted to rewrite my config without NvChad, but with Base46. In general, I can fork and rewrite it for myself, but it would be more convenient for everyone to use this repository.

At the moment, the config is tied to the load_config function built into NvChad, but it would be nice to configure it without this layer

**Comment by siduck** [comment]
@LexeyKhom ive made it for nvchad and will keep it nvchad exclusive only!! however if you still want to use it, i've got a hack. DM me on discord or telegram, i'll share you a trick, but dont tell it to anyone
