### ISSUE TITLE
poimandres theme request

### ISSUE THREAD

**Issue by kayuxx** [NvChad/base46#213]
i think it will be nice if this aesthetic theme included in NvChad 3.0

this [poimandres.nvim](https://github.com/olivercederborg/poimandres.nvim) theme is based on an [original theme](https://github.com/drcmda/poimandres-theme)

<img width="1280" alt="185516934-6db42b76-bd96-4b3f-8c20-058827b6c70f" src="https://github.com/NvChad/base46/assets/116302048/73b7ba49-9880-476b-bb55-1694950f93ab">

**Comment by kayuxx** [comment]
trying to create it

**Comment by siduck** [comment]
@kayuxcodes no need to close the issue

**Comment by kayuxx** [comment]
theme added #215
