### ISSUE TITLE
Nordic.nvim Theme request

### ISSUE THREAD

**Issue by orhnk** [NvChad/base46#214]
## Showcase

![image](https://github.com/NvChad/base46/assets/101834410/eacd326b-e75d-4711-8b93-4cfab8e7a7ea)

I have tried to recreate it on my own NvChad config but the color palette variable names makes it impossible!

> **Note** Mine turned out to be awful with mixed colors:
>
> ![image](https://github.com/NvChad/base46/assets/101834410/a78532b6-0f13-4429-a5fb-a8cca3982b76)

You can find the source code [here](https://github.com/AlexvZyl/nordic.nvim)

**Comment by siduck** [comment]
dont we  already have a nord theme and onenord theme?

**Comment by orhnk** [comment]
Yeah but there is significant difference between them.

**Comment by orhnk** [comment]
Here is the comparison:

### Nord
![image](https://github.com/NvChad/base46/assets/101834410/dc6dc577-8933-4483-8a02-be7bab34503e)

### OneNord

![image](https://github.com/NvChad/base46/assets/101834410/eefd0d6a-e24e-4ad3-91c2-98422ce7656e)

### Nordic

![image](https://github.com/NvChad/base46/assets/101834410/8bd0701e-b399-42bc-bbdc-08169b10ef86)

**Comment by orhnk** [comment]
Here Is what I have got so far:

![image](https://github.com/NvChad/base46/assets/101834410/03b277a1-9622-4b5b-913c-9995b25d14c9)

I wasn't able to make it in exact because of the NvChad's syntax grouping system.

But I am nearly satisfied with the result so [here is my config](https://github.com/UTFeight/NvChad-utf) for those are time-travelers
