### ISSUE TITLE
how to sync colors from plugins that are not in base46

### ISSUE THREAD

**Issue by ngtuonghy** [NvChad/base46#228]
Questions 1: colors not sync (barbecue.nvim)
![image](https://github.com/NvChad/NvChad/assets/116539745/bedded98-49a9-465e-b25e-e1cac3f77059)
Questions 2; icon not loaded when changing theme (nvim-web-devicons)
![1690781180044](https://github.com/NvChad/NvChad/assets/116539745/73149466-ce88-44c2-9e4e-feaf4b372301)

**Comment by siduck** [comment]
@ngtuonghy define highlight groups via hl_add https://nvchad.com/docs/config/theming

**Comment by siduck** [comment]
can you provide a video of the icon not changing?

**Comment by ngtuonghy** [comment]
this is video
https://github.com/NvChad/base46/assets/116539745/f85dff9d-d42e-42fc-9cfd-b697a6e8b312
this is my config
https://github.com/ngtuonghy/nvchad_config/blob/main/configs/overrides.lua#L204C1-L213C2

**Comment by ngtuonghy** [comment]
Has been resolved because added nvim-web-devicons the icon   https://github.com/nvim-tree/nvim-web-devicons/commit/cfc8824cc1db316a276b36517f093baccb8e799a
