### ISSUE TITLE
Customizing ayu_dark and ayu_light Themes Not Working Properly

### ISSUE THREAD

**Issue by d-mitrofanov-v** [NvChad/base46#230]
Hello! I attempted to customize the `ayu_dark` and `ayu_light` themes using the `changed_themes` configuration option, as mentioned in the [documentation](https://nvchad.com/docs/config/theming). However, the themes didn't change as expected. This seemed odd to me, especially considering that other themes were successfully changing.

**Bug Details:**
While investigating the issue, I identified a bug in the theme files for both `ayu_dark` and `ayu_light`:

- In [`ayu_dark.lua`](https://github.com/NvChad/base46/blob/e56d8b27addf13504ac112ecdb37acb5ac16065b/lua/base46/themes/ayu_dark.lua#L67), the theme name is defined with an apostrophe instead of an underscore.
- Similarly, in [`ayu_light.lua`](https://github.com/NvChad/base46/blob/e56d8b27addf13504ac112ecdb37acb5ac16065b/lua/base46/themes/ayu_light.lua#L67)

**Comment by siduck** [comment]
@d-mitrofanov-v send a PR to correct it!

**Comment by d-mitrofanov-v** [comment]
@siduck [done](https://github.com/NvChad/base46/pull/231)
