### ISSUE TITLE
Syntax highlighting colorscheme incorrect for Latex files when using vimtex

### ISSUE THREAD

**Issue by mvds314** [NvChad/base46#239]
**Describe the bug**
I want to use vimtex for syntax highlighting LaTeX, as people claim it is better that treesitter this filetype.

When I open neovim, and open a LaTeX file right away, the highlighting color do no match the NvChad theme (onedark in my case), but resembes one of the vim default themes (not sure which one).

**To Reproduce**
1. Install vimtex, set up NvChad with any theme (onedark)
```
2. Disable treesitter for latex like [so](https://github.com/lervag/vimtex/issues/2469):
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = { "html", "css", "bash", "python", "latex", "json", "lua", "vim", "yaml" },
    },
	config = function(_, opts)
	  -- https://www.reddit.com/r/neovim/comments/xqogsu/turning_off_treesitter_and_lsp_for_specific_files/
      require "nvim-treesitter.configs".setup {
	    highlight = { enable = true, -- false will disable the whole extension
                      disable = { "tex", "latex" }, -- list of language that will be disabled
					  use_languagetree = true,
					},
	  }
    end,
  },
```

4. Open neovim
5. open a Latex file, syntax highlighting does not look good (it resembles one of the vim default themes, not sure which one).
6. Then switch (leader+t+h) to the selected theme of NvChad

**Expected behavior**
Step 6 should not be required

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System: Windows 11
 - Terminal: neovim-qt

**Comment by siduck** [comment]
add event="VeryLazy" for vimtex plugin

**Comment by mvds314** [comment]
Tried it like so: `{ "lervag/vimtex", ft = "tex", event="VeryLazy"},`

But it does not solve the problem.
Syntax highlighting still looks like this (intially):
![image](https://github.com/NvChad/NvChad/assets/4789270/387bfd63-a53c-456e-ab59-ac20de86107f)
After I switch theme (manually), it looks like this:
![image](https://github.com/NvChad/NvChad/assets/4789270/dfbb4571-dff3-4d53-9f91-b6667da57a6b)
Meaning the onedark theme, as all other files look.

**Comment by siduck** [comment]
@mvds314 share your settings + a test latex file

**Comment by mvds314** [comment]
Sure, I put my NvChadConfig on [github ](https://github.com/mvds314/NvChadConfig/tree/main)

For a test file, any LaTeX file would suffice. For example, put [this ](https://mally.stanford.edu/~sr/computing/latex-example.html) code a file called example.tex, and open it right away opening neovim.

**Comment by siduck** [comment]
https://github.com/NvChad/base46/assets/59060246/09197973-7c79-4b7a-ae55-b1225aafb279

i cant reproduce this issue, also treesitter latex treesitter parser seems to provide nice highlighting, then why use vimtex?

**Comment by mvds314** [comment]
Let me check on my Linux machine later today.

**Comment by mvds314** [comment]
Treesitter doesn't seem be doing a good job for LaTeX. I'm not sure why, but [others](https://www.reddit.com/r/neovim/comments/twv055/what_do_you_use_for_syntax_highlighting_in_latex/) complain about it too.
So, my first though was to turn treesitter off for for tex files and use vimtex (as I need to install that anyway), maybe there are other solutions too.

The issue persist on my Linux machine.

Steps I followed:
- Clone my config in into ~/.config/nvim/lua/custom/....
- Start neovim (version 0.9.1-3), NvChadUpdate, MasonInstallAll, restart etc
- Paste the Latex code from the website above into neovim, save it as example.tex
- Then highlighting looks wrong (as in the image above with yellow)
- When I switch theme to onedark, it looks as it is supposed to be (the image above).

**Comment by mvds314** [comment]
I believe I fixed it. Not sure why, but my guess is my custom config was overriding the standard treesitter config.
And, I should have added the line: `dofile(vim.g.base46_cache .. "syntax")`

So that the entire config for treesitter now looks like this:
```
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = { "html", "css", "bash", "python", "latex", "json", "lua", "vim", "yaml" },
    },
    config = function(_, opts)
      -- https://www.reddit.com/r/neovim/comments/xqogsu/turning_off_treesitter_and_lsp_for_specific_files/
      dofile(vim.g.base46_cache .. "syntax")
      require("nvim-treesitter.configs").setup {
        highlight = {
          enable = true, -- false will disable the whole extension
          disable = { "tex", "latex" }, -- list of language that will be disabled
          use_languagetree = true,
        },
        indent = { enable = true },
      }
    end,
  },
```

**Comment by siduck** [comment]
yes @mvds314   the dofile code is in the   default config too
