### ISSUE TITLE
color scheme issue when nvim is set as man pager

### ISSUE THREAD

**Issue by xorgal** [NvChad/base46#240]
**Describe the bug**

When nvim is set as `MANPAGER` and opening single man page all works good. But, when opening another man page in a new buffer or just opening empty one then colors are being reset.

**To Reproduce**
Set nvim as default pager `export MANPAGER='nvim +Man!'` and open it `man nvim`
Open reference to another man page or just make a new buffer.

**Expected behavior**
Do not change color scheme.

**Screenshots**

![nvim man 1](https://github.com/NvChad/NvChad/assets/93151521/66c42f3c-319e-4e6c-b4d6-72da603b40d6)
![nvim man 2](https://github.com/NvChad/NvChad/assets/93151521/172d4df5-0b61-48a7-8ee6-9864680f4530)

**Desktop (please complete the following information):**
 - Operating System: Win 11 / WSL2
 - Terminal: Windows Terminal
 - Version of Neovim:
 ```sh
 NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```
- NvChad version: 2.0 (commit 215aa2bb2ff702014132c629d9c995246234fe0e)

**Comment by siduck** [comment]
```lua
vim.api.nvim_create_autocmd("StdinReadPre", {
  group = vim.api.nvim_create_augroup("stdinColors", {}),
  callback = function()
    vim.api.nvim_del_augroup_by_name "stdinColors"
    dofile(vim.g.base46_cache .. "syntax")
  end,
})
```

put this in custom/init.lua

**Comment by teklabania** [comment]
Thanks for your comment @siduck, but don't you think this is just a workaround? A change should be added to the code so everyone could benefit.

**Comment by siduck** [comment]
@teklabania very less people read man pages through nvim! or pipe stdin stuff into nvim so  yea, but that solution isnt a workaround. I'd have done the same in core/utils.lua's (lazy_load) function

**Comment by teklabania** [comment]
> @teklabania very less people read man pages through nvim!

Have you collected any statistics on this if you're so sure? ;)

Thanks for doing a change to core.

**Comment by siduck** [comment]
> > @teklabania very less people read man pages through nvim!
> 
> Have you collected any statistics on this if you're so sure? ;)
> 
> Thanks for doing a change to core.

i'm just assuming :p   .

if there will be more 3 users who bring up this same issue then i'll consider adding this thing into core

**Comment by xorgal** [comment]
Actually, I do agree, nvim might not be the best candidate for viewing man pages. But sometimes it's very convenient to use multiple buffers when reading large page with plenty references.

Anyways, thanks for the fix @siduck, it did work indeed!
