### ISSUE TITLE
The highlight on the float windows for "gruvbox_theme" is invisible

### ISSUE THREAD

**Issue by ivokun** [NvChad/base46#261]
Thank you for porting `gruvbox_light` to this project!
As a long-time user of NvChad and Gruvbox theme, this is the answer that I looked for.

But I have a small bummer when I find files with Telescope: the selection is not correctly highlighted, or the color is the same as the background.
Where can I change it?

Example:
![image](https://github.com/NvChad/base46/assets/13001265/684df55b-e049-41a8-a3b8-3ead9c48a1d1)

**Comment by siduck** [comment]
![image](https://github.com/NvChad/base46/assets/59060246/699043da-d5fe-4067-a9a7-be03c70cc48e)

i cant reproduce it

**Comment by ivokun** [comment]
That's weird. I'm not sure what other configs I've been set. 
But for now, I'll stick with overriding `TelescopSelection` colors.

**Comment by siduck** [comment]
comment your chadrc and check

**Comment by siduck** [comment]
also make sure nvchad is upto date

**Comment by ivokun** [comment]
@siduck 
Thanks, it seems I haven't updated the nvchad to v2.
But unfortunately still have the same problem.
I'm not sure whether there's a problem with my other configs (Alacritty + tmux) or not.

**Comment by siduck** [comment]
@ivokun try without tmux

**Comment by ivokun** [comment]
@siduck 
You are right, the problem was the tmux 😂

In case anyone have a same problem, I fixed the problem with adding this in `.tmux.conf`: `set-option -ga terminal-overrides ",xterm-256color:Tc"`


![image](https://github.com/NvChad/base46/assets/13001265/4ac87fe2-a4e8-4752-8702-9d6560796537)
