### ISSUE TITLE
All included themes have indistinct colors for comments

### ISSUE THREAD

**Issue by sasq64** [NvChad/base46#266]
**Is your feature request related to a problem? Please describe.**
I like comments to be visible.

**Describe the solution you'd like**
Include at least some themes out of the box with a more prominent color for comments (like the traditional green).

**Comment by siduck** [comment]
i have never seen green colored comments, comments are mostly greysh. Just add hl_override to your chadrc and make it green or light_grey or grey_fg2

**Comment by sasq64** [comment]
I will do that.
But just FYI, green or other more visible colors for comments are the default in Visual Studio / Visual Studio Code and all IntelliJ products for instance. The popularity of gray (subdued) seems to come from languages where comments is only used to comment out code...

**Comment by siduck** [comment]
> I will do that. But just FYI, green or other more visible colors for comments are the default in Visual Studio / Visual Studio Code and all IntelliJ products for instance. The popularity of gray (subdued) seems to come from languages where comments is only used to comment out code...

ohh didnt know that, just noticed that the default theme that come with those ides are using green color, where as many colorschems like onedark, catpuccin, everofrest etc use gray

 example
 
![image](https://github.com/NvChad/base46/assets/59060246/45ca0e01-0573-476c-98cd-83a11b66099a)
