### ISSUE TITLE
request: material deep ocean

### ISSUE THREAD

**Issue by asc11cat** [NvChad/base46#268]
https://github.com/marko-cerovac/material.nvim

It would be really cool if someone could port a 'deep ocean' variant of this theme. Thanks!
![image](https://github.com/NvChad/base46/assets/47783525/333f5603-ce77-41ee-9f12-dab334b3f51c)

**Comment by siduck** [comment]
https://github.com/NvChad/base46/issues/267

**Comment by asc11cat** [comment]
> #267

I see that the author of #197 PR have implemented only the 'darker' variation of theme and don't plan on doing other styles. Can we please keep this issue open so someone interested may take a look? Many thanks!

**Comment by siduck** [comment]
@asc11cat  just mention your variant in that issue
