### ISSUE TITLE
Adding custom theme.

### ISSUE THREAD

**Issue by mubin-thinks** [NvChad/base46#271]
**Describe the bug**
Assalamu alaikum, brother, I was trying to create a theme of my own called end (because the background color is very dark). I created a file in `.config/nvim/lua/custom/themes/end.lua` and tried to use it in the lua file. Here's the error with a screenshot:
![20240103_18h59m52s_grim](https://github.com/NvChad/NvChad/assets/101094719/5d027565-1a80-40b4-b354-f7bfcecc79b6)

Why can't I set "end" as a theme?

**To Reproduce**
1. Try creating a custom theme.

**Expected behavior**
It should just work. And get the colors from end.lua.

**Screenshots**

**Desktop (please complete the following information):**
 - Arch linux
 - Alacritty
 - NVIM v0.9.5

**Comment by siduck** [comment]
wa alaykum as salam,  that warning you see isnt a big issue, doesnt affect anything. do colors from end.lua reflect?

**Comment by mubin-thinks** [comment]
No, they don't.

**Comment by siduck** [comment]
share end.lua here, i'll test

**Comment by mubin-thinks** [comment]
Here's the lua file:
```lua
-- place the file in /custom/themes/<theme-name>.lua
-- for example: custom/themes/end.lua

local M = {}

-- M.base_30 = {
-- }

M.base_16 = {
  base00 = "#050505",
  base01 = "#101010",
  base02 = "#101010",
  base03 = "#909090",
  base04 = "#050505",
  base05 = "#adadad",
  base06 = "#adadad",
  base07 = "#adadad",
  base08 = "#828fad",
  base09 = "#ada282",
  base0A = "#82acad",
  base0B = "#82acad",
  base0C = "#ada282",
  base0D = "#9782ad",
  base0E = "#ad9082",
  base0F = "#adadad"
}

M.type = "dark" -- light / dark

return M
```

**Comment by siduck** [comment]
base30 table is empty

**Comment by mubin-thinks** [comment]
Ok, I just copied the base_30 of gruvchad and pasted it in end.lua. And it works fine. Thanks. Allah hafiz.
