### ISSUE TITLE
Color that defines the selection in a replacement

### ISSUE THREAD

**Issue by carmilso** [NvChad/base46#272]
Hi, quick question.

Does anyone know where is defined the color shown when a word is selected when you are doing a replacement? For example, if the following case I am running a conditional replacement and the focus is on the line 3, that's the color I want to find:
![image](https://github.com/NvChad/base46/assets/7313231/7cce7be3-4f2c-44bb-869f-e32482c49ae2)

**Comment by siduck** [comment]
i think its Search hl group
