### ISSUE TITLE
Porting DoomChad outside of NvChand.

### ISSUE THREAD

**Issue by GusJelly** [NvChad/base46#275]
I want to port the theme DoomChad to work outside of this plugin. Is there a *set* way to do this?
If there isn't then I'll close the issue and do it on my own so there is no need to change anything
about the plugin.

**Comment by siduck** [comment]
nvchad's doomchad is based on this https://github.com/NTBBloodbath/doom-one.nvim     

but do know that you can probably  use base46 and other nvchad plugins without nvchad from v3.0 so wait for a while!
