### ISSUE TITLE
Typescript and Lua for statement keyword not highlighted

### ISSUE THREAD

**Issue by joetifa2003** [NvChad/base46#285]
![image](https://github.com/NvChad/base46/assets/62658783/c9d0f89b-c01c-4268-a697-91e51adcb174)
Using catpuccin theme (also happens with other themes)
I have the treesitter parser installed and up-to-date.

Also, something which I don't like is the highlight of the { }, I want to make it gray or something.

Thanks for your work!

**Comment by siduck** [comment]
![image](https://github.com/NvChad/base46/assets/59060246/1b475864-bccd-4fb7-9084-3ecbc19b744a)

should look like this. I hope youve done `TSInstall javascript typescript tsx`

**Comment by siduck** [comment]
and for grey stuff https://nvchad.com/docs/config/theming

**Comment by joetifa2003** [comment]
Thanks for the quick response!

I already installed treesitter parsers, and did reinstall just in case, but didn't help.
Also tried with different terminals.

I'm using the example user config and just added a couple of plugins.

Want me to upload my config?

**Comment by siduck** [comment]
I tried example_config, it looks fine.

![image](https://github.com/NvChad/base46/assets/59060246/0437ae16-5f04-46de-9884-a3fdadbaf92b)
   
   
  your only help could be rm -rf .local/share/nvim
