### ISSUE TITLE
Comment override stopped working after update

### ISSUE THREAD

**Issue by mr-shifty** [NvChad/base46#289]
It worked before the update:

![image](https://github.com/NvChad/base46/assets/118600823/d09ac11c-e044-420b-8dd5-93fe699f01bf)

After update:

![Снимок экрана от 2024-03-06 10-25-33](https://github.com/NvChad/base46/assets/118600823/60569de0-4418-4a3c-a0ed-06083904bba7)

**Comment by siduck** [comment]
`["@comment"]`

add for this too. Cuz thats treesitter related.
