### ISSUE TITLE
bug: base46 integrations breaks colorscheme to load (v2.5)

### ISSUE THREAD

**Issue by kayuxx** [NvChad/base46#293]
**Describe the bug**
base46 integrations on `chadrc.lua` file will break the colorscheme to load, you can't apply or set another theme since you can't load it.

**To Reproduce**
1. Go to `/lua/chadrc.lua`
2. Set the base46 integrations, for e.g ```M.base46 = { integrations = { "lspsaga", "notify" } } ```
3. Save and exit nvim
4. open nvim again and try to change theme.

**Expected behavior**
apply the integrations that you've set and apply its highlights.

**Comment by siduck** [comment]
i dont get it, make a video of it.  Only those integrations will compile. So if on other places that dofile* function is calling other integrations then not our fault!

**Comment by siduck** [comment]
![image](https://github.com/NvChad/base46/assets/59060246/cc64e2fe-e148-44a8-a055-2dad60ccaff4)

So you have to remove all  instances of that dofile code and override all plugin config functions where it is used
