### ISSUE TITLE
Comment not updating in Base46HLGroupsList

### ISSUE THREAD

**Issue by cmoles** [NvChad/base46#297]
Using NvChad v2.0 / base46 v2.0:

I update my plugins and found comment highlights not working with my config.

![Screenshot 2024-03-19 205621](https://github.com/NvChad/base46/assets/158307/390d6904-b7cf-4dea-a681-82c7031f340d)

I reverted to the previous commit -- 3f2b658 -- and that seemed to fix it.

![Screenshot 2024-03-19 210255](https://github.com/NvChad/base46/assets/158307/4d273715-35c3-4db7-8368-5c9f0e756573)

Thank you for your work. Let me know if I can help!

**Comment by siduck** [comment]
`["@comment"]`

Comment is for files that dont use treesitter parsers, most of the times we just use the treesitter parser so @comment is its hlgroup

**Comment by cmoles** [comment]
That did the trick! Thank you so much!
