### ISSUE TITLE
NeoVim default theme

### ISSUE THREAD

**Issue by hubcio2115** [NvChad/base46#298]
In NeoVim 0.10 there will be a new default theme added. Is it possible to set the new default theme in base46 on neovim-nightly?

If so, how to do it?

If not I'm more than willing to create a PR that will add this functionality.

**Comment by siduck** [comment]
if you just mean it for syntax then remove the dofile code for treesitter in its config function 

or if u mean for whole then remove all instances of dofile code i.e overriding the config function of all plugins we have & main init.lua

**Comment by hubcio2115** [comment]
Thank you for the tip.
