### ISSUE TITLE
Request: Neogit Integration

### ISSUE THREAD

**Issue by teoshibin** [NvChad/base46#299]
Color integration for neogit, here's an awful image of commit diff
![image](https://github.com/NvChad/base46/assets/62151367/75c84190-fad6-4103-904a-0be678446ff3)

**Comment by siduck** [comment]
load `git` integration in your neogit config function or load it after gitsigns.nvim

`dofile(vim.g.base46_cache..'git')`

**Comment by andradei** [comment]
@siduck I did that and still have a pretty bad diff color

```lua
-- lua/configs/neogit.lua

local options = {
  signs = {
    -- { CLOSED, OPENED }
    hunk = { "", "" },
    item = { "󰁔", "󰁅" },
    section = { "", "" },
  },
}

-- Get correct diff highlighting
dofile(vim.g.base46_cache .. "git")

require("neogit").setup(options)





-- lua/plugins/init.lua

 {
    "NeogitOrg/neogit",
    cmd = "Neogit",
    dependencies = {
      "nvim-lua/plenary.nvim", -- required
      "sindrets/diffview.nvim", -- optional - Diff integration
      "nvim-telescope/telescope.nvim",
    },
    config = function()
      require "configs.neogit"
    end,
  },
```

The theme is `flexoki-light` and this is what is looks like:

![image](https://github.com/NvChad/base46/assets/2653546/61934706-7195-4480-9142-6bade86f1f34)

**Comment by siduck** [comment]
@andradei does it happen with other themes?

**Comment by andradei** [comment]
Was about to test, but neovim 0.10 just landed and neogit upgraded, breaking for me until I am able to upgrade neovim.
I decided to use lazygit instead :)

**Comment by Frestein** [comment]
> @andradei does it happen with other themes?

Yeah, it's happening.  I'm having the same problem.
![image](https://github.com/NvChad/base46/assets/85928597/75054d33-2551-4074-b430-8eabbe917915)
![image](https://github.com/NvChad/base46/assets/85928597/1941911b-7bbc-4a77-a13f-23a4b34cbf90)

**Comment by siduck** [comment]
i have a lost conversation of this issue, so show me how normal   neogit looks vs ours , i'll fix it on weekend :)

**Comment by Frestein** [comment]
> i have a lost conversation of this issue, so show me how normal neogit looks vs ours , i'll fix it on weekend :)

All the highlight groups are here: https://github.com/NeogitOrg/neogit/blob/master/lua/neogit/lib/hl.lua

**Comment by siduck** [comment]
> > i have a lost conversation of this issue, so show me how normal neogit looks vs ours , i'll fix it on weekend :)
> 
> All the highlight groups are here: https://github.com/NeogitOrg/neogit/blob/master/lua/neogit/lib/hl.lua

wow thats a lot! i'll add it on sunday

**Comment by siduck** [comment]
@Frestein 
```lua
M.base46 = {
  integrations = { "neogit" },
}
```
```lua

  {
    "NeogitOrg/neogit",
    cmd = "Neogit",
    dependencies = {
      "sindrets/diffview.nvim", -- optional - Diff integration
    },
    config = function()
      require("neogit").setup()
      dofile(vim.g.base46_cache .. "git")
      dofile(vim.g.base46_cache .. "neogit")
    end,
  }
  ```
