### ISSUE TITLE
when use `rmagatti/auto-session ` , some theme colors are incorrect

### ISSUE THREAD

**Issue by zerlei** [NvChad/base46#303]
**Describe the bug**
some colors display incorrect

**To Reproduce**
1. in nvim, set colortheme
2. quit nvim
3. re enter nvim, some colors are incorrect
4. reset colortheme ，These colors become correct

**Expected behavior**
colors are correct

**Screenshots**

https://github.com/NvChad/NvChad/assets/40014687/2cbc4a99-0726-4abc-bded-c4631a6f1d1c

**Desktop (please complete the following information):**
 - Windows11 but ssh ubuntu
 - Windows Terminal
 - Nvim v0.9.5
- NvChad v2.5
**Additional context**
my config  https://github.com/ZhaoYouYa/my-nvim/tree/me

**Comment by siduck** [comment]
did you override treesitter config function? i hope you didnt remove our dofile code which loads ts highlights

**Comment by zerlei** [comment]
> did you override treesitter config function? i hope you didnt remove our dofile code which loads ts highlights

No, I just forked `Nvchard/starter`, and added some lines in `/lua/plugins/init.lua`

```lua
{
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "vim",
        "lua",
        "html",
        "css",
        "javascript",
        "typescript",
        "tsx",
        "c",
        "cpp",
        "markdown",
        "markdown_inline",
        "cmake",
      },
    },
  },

```

**Comment by siduck** [comment]
TSInstall vue

**Comment by zerlei** [comment]
Thank you siduck! I found out that my problem was because I added a plugin called 'rmagatti/autosession'. When I commented out this plugin, everything was fine...

```lua
{
    "rmagatti/auto-session",
    init = function()
      require("auto-session").setup {
        log_level = "error",
        auto_session_enable_last_session = true,
        auto_save_enabled = true,
        auto_restore_enabled = true,
        session_lens = {
          -- If load_on_setup is set to false, one needs to eventually call `require("auto-session").setup_session_lens()` if they want to use session-lens.
          buftypes_to_ignore = {}, -- list of buffer types what should not be deleted from current session
          load_on_setup = true,
          theme_conf = { border = true },
          previewer = false,
        },
      }

      -- todo add keymap manager
      -- vim.keymap.set("n", "<leader>ss", require("auto-session.session-lens").search_session, {
      --   noremap = true,
      -- })
    end,
  },
```

**Comment by siduck** [comment]
@ZhaoYouYa yes i have faced this issue with that plugin only, either use other autosession plugins or add this in your main init.lua

```lua
dofile(vim.g.base46_cache .. "syntax")
dofile(vim.g.base46_cache .. "treesitter")
```

**Comment by zerlei** [comment]
> @ZhaoYouYa yes i have faced this issue with that plugin only, either use other autosession plugins or add this in your main init.lua
> 
> ```lua
> dofile(vim.g.base46_cache .. "syntax")
> dofile(vim.g.base46_cache .. "treesitter")
> ```

Thank you! I add this in my init.lua,This solves my problem
```lua
vim.schedule(function()
   dofile(vim.g.base46_cache .. "syntax")
   dofile(vim.g.base46_cache .. "treesitter")
 end)

```
