### ISSUE TITLE
Theme request: catppuccin flavours

### ISSUE THREAD

**Issue by akarmes** [NvChad/base46#305]
## Describe the solution you'd like

Hi. I'd like to request variations of `catppuccin` color scheme to be added to base64. Standanrd `catppuccin mocha` is a tad dark for me plus I'd like nvim to have the same color scheme as terminal and tmux. 

In short: add  catppuccin flavours `macchiato`, `frappe`, `latte`

Links:
https://github.com/catppuccin/nvim
https://github.com/catppuccin/catppuccin

**Comment by siduck** [comment]
no new catpuccin flavors will be added. You can request for all other themes but not catpuccin
