### ISSUE TITLE
lsp hints' colors and indent blankline underlines are not correct in neovim 0.10

### ISSUE THREAD

**Issue by mohammad-amin-khajeh** [NvChad/base46#306]
**Describe the bug:**
Lsp hints' colors as well as indent blank line's underlines are not correct upon opening neovim

**Steps to reproduce:**
1. Set a colorscheme
2. Close neovim
3. Reopen neovim
4. Lsp colors and ibl's underlines are messed up

**Expected behavior:**
Colors and underlines are correct

**Temporary fix:**
After entering neovim change the colorscheme or toggle the transparency using `require("base46").toggle_transparency()`

**Machine's information:**
* Linux distribution: EndeavourOS
* Neovim 0.10
* Terminal: st(tried with alacritty, and even tty, the same issue persists)
* NvChad 2.5

**Demonstrating the issue:**

https://github.com/NvChad/base46/assets/158812659/246c7864-4128-4963-9d97-7a24ea0c0e35

https://github.com/NvChad/base46/assets/158812659/20aceb56-c7c7-4702-92db-d0e9bfc9a470

**Comment by mohammad-amin-khajeh** [comment]
I managed to fix the lsp hints' colors by adding `require("nvchad.configs.lspconfig").defaults()` to my plugins/init.lua
The indent blank line problem still persists however, and it used to occur even on neovim versions prior to 0.10

**Comment by siduck** [comment]
obviously that line of code is needed

**Comment by siduck** [comment]
![image](https://github.com/NvChad/base46/assets/59060246/f2f5f5eb-f5b9-41d7-995f-270432984864)

its even there in the starter repo's config

**Comment by siduck** [comment]
as for the blankline issue, that is not from us, since their v3.0 release we have faced it while changing theme. cant do nothing about it
