### ISSUE TITLE
Error when building using a non-NvChad Config 

### ISSUE THREAD

**Issue by Lalit64** [NvChad/base46#316]
Followed the steps in https://0x0.st/Xrbn.mp4

And then I get this error when building using Lazy,

<img width="674" alt="Screenshot 2024-06-30 at 15 29 34" src="https://github.com/NvChad/base46/assets/79628080/a23fad64-88e1-46b9-9ca0-6a2b9358d617">

Edit: I don't really want the answer of "This is not really meant to be used with other configs only NvChad"

**Comment by siduck** [comment]
show your chadrc file and plugins list

**Comment by Lalit64** [comment]
Its just tinyvim with base46 

NvConfig.lua
```
local M = {}

M.ui = {
  theme_toggle = { "onedark", "one_light" },
  theme = "onedark",   -- default theme
  transparency = true,
}

M.base46 = {
  integrations = {},
}

return M
```

I am getting a new error


<img width="645" alt="Screenshot 2024-06-30 at 19 18 27" src="https://github.com/NvChad/base46/assets/79628080/a3b01c9e-a9fe-4d5f-900f-dd1e5d257edb">

**Comment by siduck** [comment]
when did you try this thing? that err was fixed in the recent commits

**Comment by ReStranger** [comment]
Same thing, but with nvchad configuration
![image](https://github.com/NvChad/base46/assets/69393944/ce8fc55c-811e-41f9-b48d-0ac7fea9141f)

**Comment by siduck** [comment]
run lazy sync again

**Comment by muddygs** [comment]
I was able to "fix" this by uninstalling (x) on base46 and installing (I) again. :Lazy sync did not solve for me.

**Comment by siduck** [comment]
the issue happened when y'all updated base46 at a commit which it was broken,  lazy sync shouldve fixed tho

**Comment by Lalit64** [comment]
<img width="618" alt="Screenshot 2024-07-21 at 12 25 12" src="https://github.com/user-attachments/assets/0269822a-7362-4e11-a4fb-3220655f7282">
<img width="639" alt="Screenshot 2024-07-21 at 12 27 55" src="https://github.com/user-attachments/assets/0e7e170a-1e08-48b5-b3ab-439c21886d89">

**Comment by siduck** [comment]
@Lalit64  
![image](https://github.com/user-attachments/assets/02d67e42-90d0-49ee-918b-732a6b0d42d0)

you need to define that global in your main init.lua before plugins

**Comment by Lalit64** [comment]
And what about for "No such theme"

**Comment by siduck** [comment]
> And what about for "No such theme"

that theme doesnt exist
