### ISSUE TITLE
Question: Theming for textstyles in markdown missing?

### ISSUE THREAD

**Issue by pema83** [NvChad/base46#326]
I try to get bold and italic texts rendered as such in markdown files.
I do have treesitter with enabled markdown and markdown_inline.
And after some Lazy syncs I finally got some highlighting going.

But still there seems to be missing something.
For example
**boldtext**
Gets just underlined when using conceallevel=2.

I found a commit to the catppuccin theme in which TreeSitter markdown parser styles? have been added.
[Link to TS support in theme commit](https://github.com/catppuccin/nvim/commit/22b34eb9f93430bc010dee1523743b62cd2700fc)
Is something like that necessary for the nvchad themes?

**Comment by siduck** [comment]
arent those old highlight groups? @lucario387

ours are here https://github.com/NvChad/base46/blob/v2.5/lua/base46/integrations/treesitter.lua

**Comment by pema83** [comment]
I have seen 
https://github.com/NvChad/base46/blob/v2.5/lua/base46/integrations/treesitter.lua
And just tried strikethrough, which indeed works
~~strrkethrough~~ is rendered correctly in ayu_light

So it works in parts :)

**Comment by pema83** [comment]
It was my mistake.
The bold font was never correctly configured in my alacritty config.
