### ISSUE TITLE
REQUEST: All catppuccin flavours

### ISSUE THREAD

**Issue by n6v26r** [NvChad/base46#327]
Currently only mocha is available. Could we get frappe, macchiato and latte too?

**Comment by siduck** [comment]
none of catpuccin flavours will be added

**Comment by n6v26r** [comment]
Why tho?

**Comment by n6v26r** [comment]
And do you accept pull requests with themes?

**Comment by siduck** [comment]
> And do you accept pull requests with themes?

no, you can request all other themes but not this . I cant tell the reason.

**Comment by qdrs** [comment]
Why can't you add these themes?
