### ISSUE TITLE
specify levels for markup.heading

### ISSUE THREAD

**Issue by realhackcraft** [NvChad/base46#347]
I'm using [Markview.nvim](https://github.com/OXY2DEV/markview.nvim) and I noticed that since they changed their code in v24.0.0 to use different hl_groups, the different heading colors no longer work with base46.

They are supposed to be multi-colored, but with base46 they are all the same color.

![Screenshot 2024-10-06 at 19 29 31](https://github.com/user-attachments/assets/f932c244-eded-4636-b10b-a27d92b76342)

![Screenshot 2024-10-06 at 19 30 41](https://github.com/user-attachments/assets/6cea9fc0-e9f4-4478-8ebe-168d23946324)

This is because base46 only defined `@markup.heading`, while markview.nvim wants `@markup.heading.1.markdown`, `@markup.heading.2.markdown`, etc.

**Fix**

Define different colors for `@markup.heading.1.markdown` through `@markup.heading.6.markdown`

**Comment by siduck** [comment]
hmmm seems like only that plugin needs that hlgroup, raise a PR and make a file in integrations dir
with
/markview.lua 
and add all the highlight group it needs

**Comment by realhackcraft** [comment]
@siduck I have this in `intergrations/markview.lua`:
```lua
local colors = require("base46").get_theme_tb "base_30"

return {
  ["@markup.heading.1.markdown"] = { fg = colors.red },
  ["@markup.heading.2.markdown"] = { fg = colors.orange },
  ["@markup.heading.3.markdown"] = { fg = colors.yellow },
  ["@markup.heading.4.markdown"] = { fg = colors.green },
  ["@markup.heading.5.markdown"] = { fg = colors.blue },
  ["@markup.heading.6.markdown"] = { fg = colors.purple },
}
```

and I added "markview" to the itergrations list in init.lua, but I'm getting a result when I run `:hi @markup.heading.1.markdown`.

I have this to load base46:
```lua
return {
  "base46",
  dev = true,
  lazy = false,
}
```

And the base46 folder is in `~/projects/`

**Comment by realhackcraft** [comment]
![Screenshot 2024-10-09 at 11 08 31](https://github.com/user-attachments/assets/b35d0048-9980-4987-b922-ff0a46cfdbc0)

**Comment by siduck** [comment]
yes that adds the support, but you need to tell base46 to compile it too. 

put the name in `M.base46.integrations` table, check `:h nvui.base46` for better doc

**Comment by realhackcraft** [comment]
I have added “markview” to local intergrations, but it still didn’t have the groups.

**Comment by siduck** [comment]
> yes that adds the support, but you need to tell base46 to compile it too.
> 
> put the name in `M.base46.integrations` table, check `:h nvui.base46` for better doc

did you do this? This just compiles the integration

To load it use dofile function, `dofile(vim.g.base46_cache .. "markview")`  , read :h nvui.base46 :disappointed:

**Comment by realhackcraft** [comment]
I checked in my `~/.local/share/nvim/nvchad/base46/` directory, but it didn't have the markview file. How can I recompile the integrations? It doesn't seem automatic.

**Comment by siduck** [comment]
did you add markview in your chadrc?

**Comment by realhackcraft** [comment]
No, but now I have added it there. To debug it, I have deleted my `~/.local/share/nvim/nvchad` directory, how do I regenerate that?

**Comment by siduck** [comment]
:/ thats the issue. 

Please read :h nvui.base46

**Comment by siduck** [comment]
`require("base46").compile()`

**Comment by realhackcraft** [comment]
Ok, that seems to have worked. `:hi @markup.headings.1.markdown` returns correct colors. However the heading colors are still the default. I will have to talk to OXY2DEV about that.

**Comment by siduck** [comment]
how are you loading the hlgroup? i hope you included marksview in chadrc

**Comment by realhackcraft** [comment]
I did and the hlgroups are loaded.

![Screenshot 2024-10-10 at 10 09 34](https://github.com/user-attachments/assets/dc69d755-970a-4329-833b-66eada806afe)

I think there's some other hlgroups taking priority over the ones I defined. I'll ask OXY2DEV.

**Comment by siduck** [comment]
go to Telescope highlights , and show results of @markup

**Comment by realhackcraft** [comment]
![Screenshot 2024-10-10 at 10 54 39](https://github.com/user-attachments/assets/3c8a0259-bd7d-4fd4-a38d-6e9c0bbdb4d7)

**Comment by siduck** [comment]
just grep in markview plugin the word `set_hl`

**Comment by siduck** [comment]
and you might find list of highlight groups

**Comment by realhackcraft** [comment]
So, I have made some progress. By putting `dofile(vim.g.base46_cache .. "markview")` in `init.lua`, markview can detect the hl groups. However, putting that in the config option for the plugin
```lua
return {
  "OXY2DEV/markview.nvim",
  ft = "markdown",
  config = function()
    dofile(vim.g.base46_cache .. "markview")

    require("markview").setup({})
  end,
  dependencies = {
    "nvim-treesitter/nvim-treesitter",
    "nvim-tree/nvim-web-devicons",
  },
}
```
Didn't work. I also tried putting it in chadrc
```lua
M.base46 = {
  ...
  integrations = {
    "markview",
  },
}
```
Which also didn't work.

**Comment by realhackcraft** [comment]
How does the `M.base64.integrations` get loaded? I know its
```lua
---@param tb Base46Integrations[]
M.load = function(tb)
  for _, v in ipairs(tb) do
    dofile(vim.g.base46_cache .. v)
  end
end
```

but how does it get called? Do I have to call nvchad.base46.load() myself or is it handled automatically?

Also, should I have `dofile(vim.g.base46_cache .. "markview")` in markview config function or no?

**Comment by siduck** [comment]
your code is right, but how are you even testing the changes? i hope you're using lazy.nvim's dev or dir spec at least. Just make the PR and then try locally

**Comment by realhackcraft** [comment]
Yeah, I'm using dev=true on base46 and have my fork of base46 in ~/projects/

**Comment by realhackcraft** [comment]
What puzzles me is:

- ✅`dofile(vim.g.base46_cache .. "markview")` in init.lua
- ❌`dofile(vim.g.base46_cache .. "markview")` in markview config
- ❌integrations = { "markview" } in chadrc.lua

**Comment by siduck** [comment]
probably it needs highlights to be loaded before the plugin loads, so i'd just load it in opts function and return table of opts if  i want to change anything in plugin or return empty table, just like what i did for whichkey spec in main nvchad repo's plugins section
