### ISSUE TITLE
Custom theme issue

### ISSUE THREAD

**Issue by nikola993** [NvChad/base46#353]
When creating a new theme in base46 project under themes folder I came across an issue with SpecialChar, the issue is that is not pulling the right color. Form the [source code](https://github.com/NvChad/base46/blob/v2.5/lua/base46/integrations/syntax.lua) it should be using base_16.base0F color but its not. 

I tried adding the changes to polish_hl like this
`
M.polish_hl = {
  SpecialChar = { fg = M.base_16.base0F },
}
`
and like this
`
M.polish_hl = {
  syntax = {
    SpecialChar = { fg = M.base_16.base0F },
  }
}
`
but with no effect.

Can someone take a look and confim if I am doing everything correctly.

In the end I added in my chadrc file change 
`
  hl_override = {
    SpecialChar = { fg = "#D7B596" },
  }
`
that did the job

This is the code from the file I added 
```lua
-- this line for types, by hovering and autocompletion (lsp required)
-- will help you understanding properties, fields, and what highlightings the color used for
---@type Base46Table
local M = {}
-- UI
M.base_30 = {
  white = "#FFFFFB",
  darker_black = "#0D0B10",
  black = "#1E1B1F", --  nvim bg
  black2 = "#141617",
  lighter_black = "#2E2C2F",
  one_bg = "#161819",
  one_bg2 = "#1f2122",
  one_bg3 = "#27292a",
  grey = "#343637",
  grey_fg = "#3e4041",
  grey_fg2 = "#484a4b",
  light_grey = "#505253",
  red = "#CD6169",
  baby_pink = "#EE6A70",
  pink = "#e8646a",
  line = "#1b1d1e", -- for lines like vertsplit
  green = "#83B28A",
  vibrant_green = "#81c19b",
  nord_blue = "#5A84BC",
  blue = "#5EA7E3",
  yellow = "#E5BF79",
  sun = "#f6dc95",
  purple = "#c58cec",
  dark_purple = "#9E77BD",
  teal = "#51AEB9",
  orange = "#D2846D",
  cyan = "#67AFC1",
  statusline_bg = "#101213",
  lightbg = "#1d1f20",
  pmenu_bg = "#78B892",
  folder_bg = "#78B892",
}

M.base_16 = {
  base00 = M.base_30.darker_black,
  base01 = M.base_30.black,
  base02 = M.base_30.lighter_black,
  base03 = "#7F807E",
  base04 = "#D1D3CC",
  base05 = "#E1E4DC",
  base06 = "#F1F5EC",
  base07 = M.base_30.white,
  base08 = M.base_30.red,
  base09 = M.base_30.orange,
  base0A = M.base_30.yellow,
  base0B = M.base_30.green,
  base0C = M.base_30.teal,
  base0D = M.base_30.blue,
  base0E = M.base_30.dark_purple,
  base0F = "#D7B596",
}

M.polish_hl = {
  syntax = {
    SpecialChar = { fg = M.base_16.base0F },
  }
}

-- set the theme type whether is dark or light
M.type = "dark" -- "or light"

-- this will be later used for users to override your theme table from chadrc
M = require("base46").override_theme(M, "leaf_dark")

return M
```

**Comment by siduck** [comment]
your code is right

**Comment by nikola993** [comment]
But the M.polish_hl is not doing anything I had to add `hl_override = { SpecialChar = { fg = "#D7B596" }, }` Inside of chadrc file to change the color of special characters, is that how it suppose to be?

**Comment by siduck** [comment]
![image](https://github.com/user-attachments/assets/4268569a-5844-432e-8f41-10200e9bccbe)

your code works for me

**Comment by nikola993** [comment]
When I delete code from chadrc this is what I get:
<img width="1139" alt="Screenshot 2024-10-15 at 12 07 16" src="https://github.com/user-attachments/assets/a576bf92-7907-4085-9322-00ee4266093e">

That color for special character is not even included in the theme colors.

Did I added the theme in the correct place?

**Comment by siduck** [comment]
why are you adding theme there :/ 

please add themes in ~/.config/nvim/lua/themes only, dont touch plugin codebase

**Comment by nikola993** [comment]
So I tried that as well but had the same result and I tried to move it to plugin to check, but it is the same in both cases.

**Comment by siduck** [comment]
i hope you are saving the files with nvim, or else nothing's gonna re-compile

**Comment by siduck** [comment]
did you change your nvim theme to leaf_dark?

**Comment by nikola993** [comment]
Lol yeah, and yeah 
<img width="520" alt="Screenshot 2024-10-15 at 12 51 22" src="https://github.com/user-attachments/assets/89051625-e20e-4b0c-b7fb-40798c09ccd8">

Every color from the theme is applied except for that one.

**Comment by siduck** [comment]
remove the hl_override, the polish_hl wont work

**Comment by nikola993** [comment]
Scenario one:
- Theme is in the  ~/.config/nvim/lua/themes with the code from first comment in the issue
- In chadrc file no hl_override is set
The color of the special char is set to some brown color that does not exist in theme or anything that I added
<img width="172" alt="Screenshot 2024-10-15 at 13 03 07" src="https://github.com/user-attachments/assets/a59b9a70-34f3-4517-b1af-c8c14bf98a22">

Scenario two:
- Theme is in the  ~/.config/nvim/lua/themes with the code from first comment in the issue
- In chadrc file hl_override is set
The color form that override is used for special characters and everything is working correctly

Scenario three:
- Theme is in the  plugin_folder/themes with the code from first comment in the issue
- In chadrc file no hl_override is set
Same as scenario one

Scenario four:
- Theme is in the  plugin_folder/themes with the code from first comment in the issue
- In chadrc file hl_override is set
Same as scenario two

**Comment by siduck** [comment]
why complicate it !! just give your theme file, i will show a video recording from scratch that its working here.

**Comment by nikola993** [comment]
I get it that it is working for you but it is not working for me any suggestions on why? I really don't have any fancy config for neovim couple of plugins and thats it, so I am not sure why it is not working for me correctly and it does for you.

Here is the file but I trust that its working on your side you don't have to make a video for it 
[leaf_dark.txt](https://github.com/user-attachments/files/17377284/leaf_dark.txt)

**Comment by nikola993** [comment]
Just to let you know everything started working today without hl_override in chadrc not sure why. Sorry for the troubles

**Comment by siduck** [comment]
all good :joy:
