### ISSUE TITLE
Can't override Comment highlight group with expected syntax 

### ISSUE THREAD

**Issue by micahkepe** [NvChad/base46#354]
Hello, for some reason in my `chadrc.lua` I can't override the `Comment` highlight group in the same manner as the other group (for example, in the picture I can override the "WinSeperator" group above just fine using ["WinSeparator"]). For the comment group I could only get it to work by using ["@comment"]. Any help would be greatly appreciated! Thank you!

<img width="414" alt="Screenshot 2024-10-17 at 9 25 02 AM" src="https://github.com/user-attachments/assets/4a992e6f-513f-4624-8968-158178c63f1f">

**Comment by siduck** [comment]
I think in lua to use special chars in key, u need to wrap it with  [ ]

**Comment by siduck** [comment]
add Comment hlgroup too, @comment is for treesitter one
