### ISSUE TITLE
Add 'neovim-plugin' as topic to the GitHub repository

### ISSUE THREAD

**Issue by Frestein** [NvChad/base46#361]
I would like to request the addition of the 'neovim-plugin' tag to this repository. This tag is necessary for the plugin to be listed on [dotfyle.com](https://dotfyle.com/), which is a valuable resource for Neovim users.

Please consider tagging the repository accordingly.

![image](https://github.com/user-attachments/assets/00ad0a20-9f56-4d46-8d96-63d54297f267)

**Comment by siduck** [comment]
done
