### ISSUE TITLE
How to edit a theme?[Solved]

### ISSUE THREAD

**Issue by kervanaslan** [NvChad/base46#371]
Hello,

This question has probably been asked before, and there’s likely a solution out there, but despite searching a lot, I just can’t find it. I’m probably not using the right keywords.

Here’s what I want to do:

I want to change the background of the selected file in the Tree section. You can see exactly which part I’m talking about in the image.

As you can see from the image, the selected Tree item has a background color that’s very similar to its own, and my eyes aren’t sharp enough to distinguish it clearly.

I would really appreciate it if you could tell me how to do it.
<img width="1288" alt="ss" src="https://github.com/user-attachments/assets/3033d580-fbd4-4bf2-88c1-fd27bd75e629" />

**Comment by siduck** [comment]
use hl_override. read :h nvui.base46

**Comment by kervanaslan** [comment]
Thank you @siduck I could fix it.


```
M.base46 = {
  theme = "vscode_dark",
  hl_override = {
    NvimTreeCursorLine = { bg = "lightbg" },
  },
}
```
