### ISSUE TITLE
Setup base46 themes with Lazyvim

### ISSUE THREAD

**Issue by AjayShanker-geek** [NvChad/base46#372]
![image](https://github.com/user-attachments/assets/605c6461-3e29-457f-add1-311a8b9eda63)

Hi, is there a working method to use base46 with lazyvim? This is from following base46 readme setup and it seems it is not working correctly. Cheers!

**Comment by siduck** [comment]
base46 doesnt have support for neotree yet as no one raised a PR nor iuse that plugin. You're free to add that integration
