### ISSUE TITLE
Issue with Latex files when Treesitter is enabled

### ISSUE THREAD

**Issue by primeapple** [NvChad/base46#53]
Hi, thanks for the awesome theme picker.

I'm currently writing my thesis in Latex and am not able to install Treesitter, as the highlighting becomes unusable:

I use chadracula, as well as [vimtex](https://github.com/lervag/vimtex).
As a reference I used the original Dracula theme: https://github.com/dracula/vim

Just Chadracula (not dracula at all, but usable)
<img width="344" alt="no_ts_chadracula" src="https://user-images.githubusercontent.com/35628420/160625289-87aa170f-2eb3-4c48-934e-40996a89923c.png">
Just Dracula (everything just pink and white)
<img width="344" alt="no_ts_dracula" src="https://user-images.githubusercontent.com/35628420/160625296-938fe524-0128-4b0e-ab9e-267d9dd96afa.png">
Treesitter + Chadracula (not usable, since the text is all orange)
<img width="344" alt="ts_chadracula" src="https://user-images.githubusercontent.com/35628420/160625299-e6cbcc96-25df-4108-a099-922ea1d48b5c.png">
Treesitter + Dracula (best config)
<img width="344" alt="ts_dracula" src="https://user-images.githubusercontent.com/35628420/160625303-195ff28f-8b8b-4621-81ec-5fa8ced8ac6e.png">

I think it might be a problem with Treesitter, since I also have some issues with nested tables in `.lua` files, where everything is just orange as well. I have the same problems (colorful text) with all the other colorschemes

**Comment by siduck** [comment]
u can improve the chadracula and make it look like dracula

**Comment by primeapple** [comment]
The issue with Treesitter in latex is present for *all* themes.
It is not an issue with `vimtex` I just tested it.

**Comment by siduck** [comment]
do u get this issue with lunarvim?

**Comment by primeapple** [comment]
I don't use lunarvim, so no Idea :grin:

**Comment by siduck** [comment]
try with it then ._.

**Comment by primeapple** [comment]
So I post a bug with this repo. You ask me to check if it occurs on $OTHER_UNRELATED_REPO.

Could you please at least explain, in more than a single sentence, why I should go through the process of installing and trying Lunarvim, when the issue is in THIS repo?

**Comment by siduck** [comment]
> So I post a bug with this repo. You ask me to check if it occurs on $OTHER_UNRELATED_REPO.
> 
> Could you please at least explain, in more than a single sentence, why I should go through the process of installing and trying Lunarvim, when the issue is in THIS repo?

it might be a pain to prepare a minimal config to test this so i suggested trying the error on lunarvim as its pre-setup, it'd give me a general idea if this issue's nvchad only or not

**Comment by max397574** [comment]
just use treesitter playground to see which highlight groups are used and change one of them if it's "unusable" if you have two things with the same color

**Comment by siduck** [comment]
@primeapple  do you still face this issue?

**Comment by primeapple** [comment]
Yes it is still broken. But thanks for the rewrite :)
Please leave this issue open, when I'll have more time, I'll look into TS Playground.

**Comment by siduck** [comment]
> Yes it is still broken. But thanks for the rewrite :) Please leave this issue open, when I'll have more time, I'll look into TS Playground.

do you have the issue with other configs?

**Comment by siduck** [comment]
oh nvm i actually read the issue now lol, So this seems like a theme issue? i think chadracula isnt 100% dracula, you can send a PR for it!

**Comment by primeapple** [comment]
This is not a theme issue. I have the problem with any other theme, the color of the text is the same as the one of the commands, in any theme I try.

**Comment by siduck** [comment]
oh ._.

**Comment by primeapple** [comment]
I made a video.

My guess is that we need to set a Treesitter Color for `text` probably in https://github.com/NvChad/base46/blob/master/lua/integrations/treesitter.lua
But I'm not really used to Treesitter styling.

https://user-images.githubusercontent.com/35628420/168005879-6e3bb0dc-fb32-4cae-b94c-476ef98496ea.mp4

**Comment by siduck** [comment]
we already do that 

![image](https://user-images.githubusercontent.com/59060246/168027586-a86d698f-b66c-4ee8-81e9-52c827f904e8.png)

**Comment by primeapple** [comment]
I'm sorry. Please set a TreeSitter highlighting for `word` not `text`. Allthough text does not seem to work correctly, too, since it should be white in my video but it is orange?

**Comment by siduck** [comment]
weird +_+

**Comment by primeapple** [comment]
Can you try adding a seperate Color for `text`? Maybe it defaults to orange somehow.
I can try too, if you explain how to do this in a running neovim.

**Comment by siduck** [comment]
> Can you try adding a seperate Color for `word`? Maybe it defaults to orange somehow. I can try too, if you explain how to do this in a running neovim.


 cd .local/share/nvim/site/pack/packer/opt/base46/
 
 and in the lua dir u will see integrations/treesitter.lua 
 
 Thats just a table of highlights with their fg/bg colors, try adding your thing there. 
 
 for now hardcode the color i.e add orange hex color, if it works then we'll work on this

**Comment by primeapple** [comment]
Holy ****.
This seems to be an issue of the latex parser of treesitter.
No idea why other colorschemes handle this better...

See this issue: https://github.com/latex-lsp/tree-sitter-latex/issues/44

I'll wait until they fix it, then we can close it.

**Comment by primeapple** [comment]
This is fixed
