### ISSUE TITLE
Treesitter base46

### ISSUE THREAD

**Issue by GreatestOfAllTimee** [NvChad/base46#58]
Does Nvchad really need [builtin Treesitter highlight](https://github.com/NvChad/base46/blob/master/lua/integrations/treesitter.lual)? I do not think so. Yes user can override their own highlights but it seems irrelevant, it just triggers problems. The current Nvchad/base46 with the builtin Treesitter highlights looks like less color than before. If user wanna change their TS highlight just using Nvchad handler _(if the handler exist, if not than make one rather than user need to explore deep what is going on TS side)_ https://nvchad.github.io/config/Custom%20config#override-default-highlights. Example:

```lua
-- custom/override.lua
return {
   TSKeyword = {
      fg = "#9AA2C3",
      sp = "none",
      italic = true,
   },
}

-- custom/chadrc.lua
local override_highlight = require "custom.override"

local M = {}

M.ui = {
     hl_override = override_highlight,
}
```

---

### Before (`rust`)
![image](https://user-images.githubusercontent.com/73665622/166419870-5d653272-89dc-46ba-a254-f916a4abb038.png)

### After (`rust`)
![image](https://user-images.githubusercontent.com/73665622/166419997-caa47b1d-61ca-4b31-a2d5-fc13991bce11.png)

---

### Before (`bash`)
![image](https://user-images.githubusercontent.com/73665622/166420703-fae61d47-80bd-4c42-873b-0a8914402d59.png)

### After (`bash`)
![image](https://user-images.githubusercontent.com/73665622/166420791-e0de0ebb-6397-4670-b290-b3fe453d5aaa.png)

---

### Before (`python`)
![PY_Escape](https://user-images.githubusercontent.com/73665622/166421457-d782c010-6757-4874-ad35-9eee40420343.png)

### After (`python`)
![image](https://user-images.githubusercontent.com/73665622/166421029-a3e35859-f692-4b05-9089-b84c73ecb573.png)

**Comment by siduck** [comment]
@GreatestOfAllTimee did you remove the treesitter integrations file and checked it?

**Comment by GreatestOfAllTimee** [comment]
I did

**Comment by siduck** [comment]
hmm I see, afaik treesitter is linked to most default highlights ( defined in syntax.lua ). So it looks good without treesitter integration right? just confirming @GreatestOfAllTimee

**Comment by GreatestOfAllTimee** [comment]
I think user don't mind if Nvchad provide TS integration highlight but I guess you need to handle all the TS Query. if you just handle certain TS query than maybe it messed up something. Example they handle all TS default highlight https://github.com/sharpicx/dotfiles/blob/a962e92f7b7f8d205478f77685b7e47b85771980/.config/nvim/lua/config/colorschemes/catppuccin.lua.

**Comment by GreatestOfAllTimee** [comment]
when dealing with colors (highlights) more difficult than write if statement in [Brainf**k](https://minond.xyz/brainfuck/)

**Comment by siduck** [comment]
I wanted to add treesitter integration to make themes more colorful!

**Comment by siduck** [comment]
but it did the opposite, i couldnt notice

**Comment by siduck** [comment]
I wanted to make tour themes adhere to default themes

**Comment by GreatestOfAllTimee** [comment]
> I wanted to make our themes adhere to default themes

I can't argue that, probably good idea for Nvchad feature. If it is, just handle all query highlights and in chadrc.lua user can disable default TS highlight OR override default hightlight

**Comment by siduck** [comment]
if themes look colorful without treesitter integration then I will remove it but however each theme will add its own treesitter highlights ( not all ) but some so we could adhere to original themes or be better than original theme 

I failed to replicate this theme even with treesitter bruh 

https://gitlab.com/snakedye/chocolate/-/raw/master/desktop.png

**Comment by GreatestOfAllTimee** [comment]
> if themes look colorful without treesitter integration then I will remove it but however each theme will add its own treesitter highlights ( not all ) but some so we could adhere to original themes or be better than original theme

I don’t mind if you want to add a default TS highlight for each themes, but don’t you think it’s a waste of time? if this is really the case, I appreciate the action you take even though it may introduce new issues to users (need to avoid silly issues that we can't handle)

**Comment by siduck** [comment]
I dont mean adding all of the ts highlight for each theme, for example the base16 convention makes it really difficult to color syntax like its able to use 7-9 colors only as the rest are just grey and black. 

So for example if onedark's og theme's variable color is blue, but our's is white then if I had to override this thing then I would add ``` TSVariable = { fg = blue }```

But this approach is wrong, now all the theme's variable color will be blue which is not a good thing + it'll get the plugin far from original theme.

So what i would do is add tsvariable blue to onedark only . This way I could see what's missing in our onedark implementation vs original theme then we could make it prettier!. 

Yes this might be time consuming so Im going to polish one theme per day so v2.0 gigachad release could be done after 1 more month ig

**Comment by siduck** [comment]
does treesitter integration look colorful after this? https://github.com/NvChad/base46/pull/59

**Comment by GreatestOfAllTimee** [comment]
it does, I didn't release it was a simple mistake

![image](https://user-images.githubusercontent.com/73665622/166447244-5c0e757d-cdc7-494d-917d-8c49ff3c2e55.png)
