### ISSUE TITLE
loop 'require' between base46.get_colors and hl_themes.xx ??

### ISSUE THREAD

**Issue by pqhchan** [NvChad/base46#66]
got error 'loop or previous error loading module', it would be ok when I commented the line `M = require("base46").override_theme(M, "onedark")` in hl_themes.xx, so maybe a loop 'require' exists between base46.get_colors and hl_themes.xx ?
![image](https://user-images.githubusercontent.com/19503854/167764574-0eb3392a-74f2-44a3-8dfb-e32fbbeb1bee.png)

**Comment by siduck** [comment]
i cant reproduce the error

**Comment by siduck** [comment]
u need to comment out that line when  u add custom themes

**Comment by siduck** [comment]
oh u wanted to require that file? its not posssible

**Comment by siduck** [comment]
https://nvchad.github.io/config/Custom%20config#override-default-highlights

you can use base_30 colors without importing them
