### ISSUE TITLE
BUG: Latest commit breaks custom theme folder

### ISSUE THREAD

**Issue by LeonHeidelbach** [NvChad/base46#68]
@siduck This commit  81209f4fec2409036b775c624a5b3e28fd7be272 breaks loading themes from the `custom.themes` folder.

![Screenshot_20220514_121850](https://user-images.githubusercontent.com/55194243/168421666-fc5b4ebc-43d2-430a-9ce4-fa361c54cf01.png)

**Comment by siduck** [comment]
@LeonHeidelbach this doesnt work with whichkey for me 

```lua
map("t", "jk", "<C-\\><C-n>")
```

can u try it? it just prints C-\

**Comment by siduck** [comment]
oops that change gives this 

![image](https://user-images.githubusercontent.com/59060246/168422192-2690bd2b-754b-4924-b18d-4b87fe9b8df8.png)

**Comment by siduck** [comment]
should be fixed now o_o
