### ISSUE TITLE
Error message `attempt to concatenate local 'name' (a nil value)

### ISSUE THREAD

**Issue by primeapple** [NvChad/base46#70]
Seems like yesterdays commit broke something.
I just `:PackerSynced` and got the following errors in NvChad:

```
packer.nvim: Error running config for base46: ...al/share/nvim/site/pack/packer/opt/base46/lua/base46.lua:7: attempt to concatenate local 'name' (a nil value)
packer.nvim: Error running config for feline.nvim: ...al/share/nvim/site/pack/packer/opt/base46/lua/base46.lua:7: attempt to concatenate local 'name' (a nil value)
```

I use `chadracula` as main theme, no further configs for `base46` or `feline.nvim`

**Comment by primeapple** [comment]
To at least work in the moment, add
```
M.plugins.remove = {
        "NvChad/base46",
        "feline-nvim/feline.nvim"
    }
```
to your `chadrc.lua`, save, do `:PackerSync`, and select another colorscheme via `:colorscheme ...`
You may have to restart in between these steps.

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/168538901-473803ea-4858-49a9-930f-8b52c58977e1.png)

works fine here, i cant produce the error

**Comment by siduck** [comment]
please when you do packersync, make sure to do leader uu before it :/
