### ISSUE TITLE
add rosepine theme

### ISSUE THREAD

**Issue by siduck** [NvChad/base46#74]

**Comment by bryant-the-coder** [comment]
https://github.com/bryant-the-coder/nvim-base16.lua/blob/master/lua/hl_themes/rose_pine.lua
https://github.com/bryant-the-coder/nvim-base16.lua/blob/master/lua/themes/rose_pine-base16.lua

**Comment by siduck** [comment]
Make a PR for this :)

**Comment by bryant-the-coder** [comment]
i know buddy :) i can make rose_pine plus ayu. u can polish it sooner or later :)))

**Comment by siduck** [comment]
yep made pr for those, I'll polish them at the time of merging itself

**Comment by bryant-the-coder** [comment]
kk

**Comment by siduck** [comment]
https://github.com/NvChad/base46/commit/1bc02bfb683aa14893acd28768ac5e50c64422f6
