### ISSUE TITLE
Add ayu-theme

### ISSUE THREAD

**Issue by songww** [NvChad/base46#76]
https://github.com/Luxed/ayu-vim

**Comment by siduck** [comment]
so many theme requests, please add a PR for them ;(

**Comment by siduck** [comment]
takes me hours to make a theme perfect on nvchad, isnt a simple task

**Comment by siduck** [comment]
i will improve one existing theme per day https://github.com/NvChad/base46/issues/67 so it can take more than a month

**Comment by songww** [comment]
Are there any guidelines for making a theme? I tried all afternoon yesterday and made no progress.

**Comment by songww** [comment]
If there is no time you can ignore my request.

**Comment by siduck** [comment]
> Are there any guidelines for making a theme? I tried all afternoon yesterday and made no progress.

https://github.com/NvChad/base46#contribute-for-new-themes

**Comment by bryant-the-coder** [comment]
@siduck u can just copy from mine for the ayu theme. https://github.com/bryant-the-coder/nvim-base16.lua/blob/master/lua/hl_themes/ayu-dark.lua

**Comment by siduck** [comment]
> @siduck u can just copy from mine for the ayu theme. https://github.com/bryant-the-coder/nvim-base16.lua/blob/master/lua/hl_themes/ayu-dark.lua

cool but i need the 16 colors too + takes some time to polish the original theme

**Comment by bryant-the-coder** [comment]
> > @siduck u can just copy from mine for the ayu theme. https://github.com/bryant-the-coder/nvim-base16.lua/blob/master/lua/hl_themes/ayu-dark.lua
> 
> cool but i need the 16 colors too + takes some time to polish the original theme

i have it all in that repo :D

**Comment by siduck** [comment]
done https://github.com/NvChad/base46/commit/1bc02bfb683aa14893acd28768ac5e50c64422f6
