### ISSUE TITLE
custom statusline is not loaded when toggle theme

### ISSUE THREAD

**Issue by lixvbnet** [NvChad/base46#77]
**Describe the bug**
Possible to load custom statusline when toggle/change theme?

I have following config in chadrc to use custom statusline:
```lua
M.plugins = {
    user = {
          ["feline-nvim/feline.nvim"] = {
              config = function()
                  require "custom.plugins.statusline"
              end,
          },
    },
}
```

but when toggle/change theme, it changes back to default statusline. Kind of weird, I have to quit NVIM and enter again to have my custom one.

**To Reproduce**
configure custom statusline, PackerSync
change theme.

**Expected behavior**
custom statusline is loaded instead of default one.

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System
 - Terminal
 - Version of Neovim

**Additional context**

**Comment by siduck** [comment]
moved the issue there as this is a theme issue

**Comment by siduck** [comment]
@lixvbnet  make sure you use these highlight groups https://github.com/NvChad/base46/blob/master/lua/integrations/feline.lua or add your own 


example https://github.com/NvChad/NvChad/blob/main/lua/plugins/configs/statusline.lua#L59
