### ISSUE TITLE
Themes are too hard to see

### ISSUE THREAD

**Issue by nullchilly** [NvChad/base46#78]
# Radium
![radium](https://user-images.githubusercontent.com/56817415/169582466-d8a5f860-d1c9-42a1-8478-ba9932d12a12.png)

- Top right window with C++ has too many red brackets and parentheses
- vim-matchup uses white bg...
- Can barely see Visual (Selected texts)

# Tokyonight
![tokyonight](https://user-images.githubusercontent.com/56817415/169582481-a6ce9990-4195-4b78-8f20-fb0d818be0e8.png)
- Brackets and parentheses actually fit nicely with the theme
- vim-matchup still using white bg instead of grey?
- Can see Visual easily

# Help to modify
![image](https://user-images.githubusercontent.com/56817415/169588204-751921a4-25d0-48df-bc7a-b359131d1a6c.png)
I attempted to modify base0F to the same as tokyonight's and make MatchParen only show fg and Visual to base04

However, I don't have a sense of color. While it ended up much clearer to my eyes at the same time it is uglier. Can you help me out :<

**Comment by siduck** [comment]
i will revert the change that made matchparen white, does this look good to you?

![image](https://user-images.githubusercontent.com/59060246/169627305-f3dc6891-e29b-480c-9d11-4d806781ef34.png)

**Comment by nullchilly** [comment]
This is the old MatchParen highlight
```lua
   MatchParen = {
      bg = theme.base03,
   },
```
I think `bg = theme.base02` (same as Visual is better)
![image](https://user-images.githubusercontent.com/56817415/169635780-6f6bfef9-ee44-418d-9902-6edea028cb79.png)

While it is true that darker looks better, it is still horrible on super dark theme.
On the left is radium theme, you can barely even see the visual selection. I will go crazy daily driving this

![image](https://user-images.githubusercontent.com/56817415/169635222-29f36012-0fb1-4a1b-b7ef-c91ba7eb197d.png)

On the right is what I want it to look like, a clear visual selection,  please take this into consideration. While I can always override colors by myself it's undeniable that the theme lacks too much function just for the look of it.

**Comment by siduck** [comment]
@nullchilly It will take a month for me to polish all the themes https://github.com/NvChad/base46/issues/67 so you need to wait ._.
