### ISSUE TITLE
Wrong colors in diffmode

### ISSUE THREAD

**Issue by tmaegel** [NvChad/base46#84]
The onedark theme of nvchad does not highlight colors correctly in diffview.
- The changed lines will not be color like in the second picture.
- And the used colors for DiffAdd, DiffChange, DiffDelete are not right colors (e.g. red) from the theme.

Started neovim diff mode with configured nvchad and onedark-theme.
![image](https://user-images.githubusercontent.com/9661381/172013168-c4f0e8f2-3c4d-4a7f-aa13-7274ad85aae9.png)

Started neovim diff mode with disables plugins and options.
![image](https://user-images.githubusercontent.com/9661381/172013002-21f2134a-268f-4455-8810-276bb50365d8.png)

Are these colors not taken into account by the theme? How can I override them?

UPDATE:
Theses Colors are not set in de the default themes. I overwrited the following colors and that solves the problem for me.

```
DiffAdd = {
  fg = "none",
  bg = colors.diff_add,
},
DiffChange = {
  fg = "none",
  bg = colors.diff_change,
},
DiffChangeDelete = {
  fg = "none",
  bg = colors.diff_delete,
},
DiffDelete = {
  fg = "black",
  bg = colors.diff_delete,
},
DiffText = {
  fg = "none",
  bg = colors.diff_text,
},
GitSignsAdd = {
  bg = "black",
},
GitSignsChange = {
  bg = "black",
},
GitSignsDelete = {
  bg = "black",
},
SignColumn = {
  bg = "black",
},
FoldColumn = {
  bg = "black",
}
```

**Comment by siduck** [comment]
https://github.com/NvChad/base46/blob/a8ac8880e2b3f962e225af4399a5d9ffa5701cde/lua/integrations/nvchad.lua#L49
