### ISSUE TITLE
Error running config for base46

### ISSUE THREAD

**Issue by CaptainBeidou** [NvChad/base46#86]
Got the following error after doing :PackerSync
![001](https://user-images.githubusercontent.com/101026247/174000322-ab33e756-c73b-4906-a193-49be0a6bddfb.jpg)

**Comment by siduck** [comment]
try doing a clean install

**Comment by redirect11** [comment]
I have the same problem. What do you mean by try doing a clean install?

**Comment by siduck** [comment]
clean install nvchad

**Comment by CaptainBeidou** [comment]
Thanks, that works. Remove the nvim configuration directories
`rm -rf ~/.config/nvim`
`rm -rf ~/.local/share/nvim`
`rm -rf ~/.cache/nvim`
And then re-install [nvchad](https://nvchad.github.io/getting-started/setup)
