### ISSUE TITLE
Overriding one part of styling for highlight group clears rest of the style

### ISSUE THREAD

**Issue by JulesNP** [NvChad/base46#87]
Since the update a few days ago, comments no longer show in the correct color when I first load NvChad, but display correctly if I switch the theme and then change it back.

I have an hl_override set up in my chadrc.lua to make comments italic. This never affected the color of comments before the update, but now it seems if there is an override of any aspect, it's clearing all the styles associated with the highlight group, since commenting out my override fixes the issue.

```
M.ui = {
   hl_override = {
      Comment = { italic = true },
   },
}
```

**Comment by siduck** [comment]
i will look onto this today, thx for reporting
