### ISSUE TITLE
Catppuccin Latte

### ISSUE THREAD

**Issue by phdhary** [NvChad/base46#89]
hey man love all your neovim's work!
I wonder if **Catppuccin Latte** theme (which is a light variant out of 4) will be added in the future. I've been trying to recreate them by referencing their palletes and translate it to base 46 but can't seem to get it right. You can ignore this tho if it's a lot of work.

**Comment by siduck** [comment]
i'll try

**Comment by siduck** [comment]
done https://github.com/NvChad/base46/commit/b24bc13dbe6a6fb1bb98ad718997794c2fcb1aee

**Comment by faabiosr** [comment]
Will be awesome having this theme!

**Comment by siduck** [comment]
@faabiosr no catppuccin themes will be added no matter what, I'll add thousands of other themes you want but not that one, I refuse to elaborate

**Comment by ryanmsnyder** [comment]
@siduck I noticed you removed the Catppuccin Latte theme from this repo. Also saw you mentioned not adding any Catppuccin variants on Reddit too, so you must be pretty adamant about it. Is there something I should be aware of before I attempt to port over Catppuccino Macchiato?

**Comment by siduck** [comment]
@ryanmsnyder you can port it for yourself locally, but I will not add it in the base46 repo
