### ISSUE TITLE
Customize single cursor color

### ISSUE THREAD

**Issue by bluexnine** [NvChad/base46#93]
I am trying to change the cursor block color to always be red. Currently on my set up the cursor color change based on the syntax highlighting.  Is there a way to override the cursor block color. I have tried the following code but it did not work. I am looking for a more elegant solution that would override this in chadrc.lua.

<path to plugin>/base46/integrations/defaults.lua

`
   Cursor = {
      fg = colors.white,
      bg = colors.red,
   },
`

**Comment by siduck** [comment]
https://nvchad.github.io/config/theming#override-default-highlight-groups
