### ISSUE TITLE
NeoSolarized theme

### ISSUE THREAD

**Issue by Blxckmage** [NvChad/base46#95]
can we have this theme on base46? 🐱 https://github.com/overcache/NeoSolarized

**Comment by siduck** [comment]
sure but it will take time

**Comment by Blxckmage** [comment]
> sure but it will take time

okayy!! i cant wait ^^

**Comment by gmmoose20** [comment]
noice!! me too 🙌

**Comment by siduck** [comment]
hi guys, dont we already have solarized dark theme?

**Comment by Blxckmage** [comment]
ah i forgot to close it, sorry siduck
and thanks for the solarized theme, have a good day<3
