### ISSUE TITLE
bearded arc theme

### ISSUE THREAD

**Issue by Pikachuuu-codes** [NvChad/base46#98]
https://github.com/BeardedBear/bearded-theme/

hi @siduck, great work you did there on nvchad. appreciate it.

i have one favor, can you port bearded theme arc? it would be great if you port it :)

**Comment by siduck** [comment]
@Pikachuuu-codes yes! but it will take a month or two :p

**Comment by siduck** [comment]
or you can check this https://github.com/NvChad/base46#contribute-for-new-themes , I'll improve your PR

**Comment by Pikachuuu-codes** [comment]
hey thanks @siduck , i am fairly new to nvchad and this neovim ecosystem. and plus i have exams soon. so i wont be having the time to port. sorry !!

**Comment by siduck** [comment]
@Pikachuuu-codes i know i am late, this theme has been added in dev branch
